### ISSUE TITLE
Allow the use of regex or *.txt in allowlist requirements

### ISSUE THREAD

**Issue by mbacicc** [pypa/bandersnatch#1032]
It would be nice to have the possibility to do this:

```
[allowlist]
requirements_path = /requirements
requirements =
    *.txt
```
Or provide a regex to find for specific files by changing this function:

https://github.com/pypa/bandersnatch/blob/8d277d3dc1bfc23fbd8b851cae73830e29fc1d26/src/bandersnatch_filter_plugins/allowlist_name.py#L107

**Comment by cooperlees** [comment]
This is called globbing. I am ok with this been added as long as it's tested and supported on all platforms.

pathlib is prob the best library to use here: https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob
