### ISSUE TITLE
Support 3.10

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#1054]
- Seems we have issues with S3 plugin with 3.10

Need all CI to pass with 3.10 ... today it does not.

**Comment by isidentical** [comment]
This should be hopefully fixed by liormizr/s3path#95

**Comment by cooperlees** [comment]
> This should be hopefully fixed by [liormizr/s3path#95](https://github.com/liormizr/s3path/pull/95)

Sweet - Once this is merged and released I'll add our CI here to run 3.10.
