### ISSUE TITLE
index.html not updated

### ISSUE THREAD

**Issue by ktry** [pypa/bandersnatch#1060]
Our bandersnatch 5.0.0 synchronized pypi mirror is roughly 9TB in size and is many years old. We encountered several packages like `Products.CMFPlone` that are missing links for some versions in their `web/simple/Products.CMFPlone/index.html` and `web/simple/products.cmfplone/index.html` files, yet those package versions are present under `web/packages` and are listed in web/json/products-cmfplone. The index.html files have a date of 4/9/2019 while the json file is dated 11/17/2021. We've run `bandersnatch mirror --force-check` and `bandersnatch verify --delete --json-update` in an effort to correct this but no joy. What is the best way to update the index.html files?

**Comment by ktry** [comment]
I've started writing a tool to rebuild the index.html files from the json files. In scanning the first 10000 packages, I found 140 packages had incomplete index.html files. Most of those index files have modification timestamps from several years ago. However, two them have timestamps from this month, specifically, `DocumentTemplate` 2021-11-17 and `file-converter-fgms` 2021-11-06.

**Comment by cooperlees** [comment]
Hi,

Thanks for reporting. This feel like a bug that both `sync` and `verify` should fix.

We should get debug runs of the broken packages html via something like  `bandersnatch sync Products.CMFPlone ...` to try workout why we're not getting correct html.

If you could supply me with a list of the broken packages I'll create a mirror with only them `allowlisted` to see if I too can get broken html. If you have time to try this and debug to, PRs fixing this will be accepted and I'll ship a new version. We shouldn't need to write a side tool - bandersnatch shoudl have ways to fix (and even detect - hello `verify`) this brokenness ...

**Comment by ktry** [comment]
Thanks for the reply! Turns out this was my bad, not really a problem.

We encountered index issue trying to do an offline build of an old version of Plone. The buildout script looks for packages like `simple/Products.CMFPlone/index.html` but failed due to stale instances of `Products.CMFPlone/index.html` (and `products.cmfplone/index.html`).

But as PEP 503 details, our mirror also has `simple/index.html` and `simple/products-cmfplone/index.html`. Both of those are correct. I'll add a ReWrite rule to our web server to map the legacy names to PEP 503.

We have `cleanup = true` in `/etc/bandersnatch.conf`. When I just ran `bandersnatch --debug sync Products.CMFPlone`, it deleted `simple/products.cmfplone` but not `simple/Products.CMFPlone`. I restored `simple/products.cmfplone` from a ZFS snapshot and reproduced the behavior with another run of `bandersnatch --debug sync Products.CMFPlone`:

`2021-11-28 08:02:31,476 DEBUG: Running Non PEP503 path cleanup for products.cmfplone (mirror.py:425)`
`2021-11-28 08:02:31,478 INFO: Attempting to cleanup non PEP 503 simple dir: /mirror/sites/PyPI/web/simple/products.cmfplone (mirror.py:436)`
`2021-11-28 08:02:31,486 DEBUG: /mirror/sites/PyPI/web/simple/products.cmfplone does not exist. Not cleaning up (mirror.py:433)`   **?????, odd message.**
`2021-11-28 08:02:31,487 DEBUG: Package syncer 0 emptied queue (mirror.py:133)`
`2021-11-28 08:02:31,487 INFO: Generating global index page. (mirror.py:481)`

Previous runs of `bandersnatch --force-check mirror` did not remove `simple/products.cmfplone` and the package wasn't listed in the logfile. **Should such a run have removed it? Should clean = true also remove the mixed-case directories under simple?**

Incidentally, I edited `bandersnatch_storage_plugins/filesystem.py` to disable `logger.debug(f"Read chunk: {chunk!s}")` as that produces tons of output.

42 of the of the 336864 packages in our PyPI mirror had inconsistencies between the json file and the PEP 503 index.html file. Our old logs report download errors with the few cases that I looked at, e.g., `pywapor`. Running `bandersnatch sync pywapor` corrected the inconsistency. Same for the others.

Thanks for all of your work on bandersnatch! Great improvements over the years.

**Comment by cooperlees** [comment]
> Thanks for the reply! Turns out this was my bad, not really a problem.
> 
No problems. This happens.

> We encountered index issue trying to do an offline build of an old version of Plone. The buildout script looks for packages like `simple/Products.CMFPlone/index.html` but failed due to stale instances of `Products.CMFPlone/index.html` (and `products.cmfplone/index.html`).
> 
> But as PEP 503 details, our mirror also has `simple/index.html` and `simple/products-cmfplone/index.html`. Both of those are correct.
> 
> We have `cleanup = true` in `/etc/bandersnatch.conf`. When I just ran `bandersnatch --debug sync Products.CMFPlone`, it deleted `simple/products.cmfplone` but not `simple/Products.CMFPlone`. I restored `simple/products.cmfplone` from a ZFS snapshot and reproduced the behavior with another run of `bandersnatch --debug sync Products.CMFPlone`:
> 
So if `sync` (which is just argument supplied packages running same code as `mirror` skipping the xmlrpc call) is executed bandersnatch should delete the non normalized dirs, not the other way. If we are, we should fix this

> `2021-11-28 08:02:31,476 DEBUG: Running Non PEP503 path cleanup for products.cmfplone (mirror.py:425)` `2021-11-28 08:02:31,478 INFO: Attempting to cleanup non PEP 503 simple dir: /mirror/sites/PyPI/web/simple/products.cmfplone (mirror.py:436)` `2021-11-28 08:02:31,486 DEBUG: /mirror/sites/PyPI/web/simple/products.cmfplone does not exist. Not cleaning up (mirror.py:433)` **?????, odd message.** `2021-11-28 08:02:31,487 DEBUG: Package syncer 0 emptied queue (mirror.py:133)` `2021-11-28 08:02:31,487 INFO: Generating global index page. (mirror.py:481)`
> 
> Previous runs of `bandersnatch --force-check mirror` did not remove `simple/products.cmfplone` and the package wasn't listed in the logfile. **Should such a run have removed it? Should clean = true also remove the mixed-case directories under simple?**
> 
It's meant to only cleanup the non normalized (mixed case etc.) directories and contents.

> Incidentally, I edited `bandersnatch_storage_plugins/filesystem.py` to disable `logger.debug(f"Read chunk: {chunk!s}")` as that produces tons of output.
> 
I'd take a PR to remove this. I feel this is to much spam for general debugging. We should add this if we're worried about bits going being written correctly

> 42 of the of the 336864 packages in our PyPI mirror had inconsistencies between the json file and the PEP 503 index.html file. Our old logs report download errors with the few cases that I looked at, e.g., `pywapor`. Running `bandersnatch sync pywapor` corrected the inconsistency. Same for the others.
> 
Glad this worked as we'd hoped.

> Thanks for all of your work on bandersnatch! Great improvements over the years.
Awesome - Thanks. It's hard for me these days as I don't run it anywhere.

I really need to get 5.1.0 running for the Official PyPI Disaster Recovery mirror one day (it's on a really old version).

**Comment by cooperlees** [comment]
Please reopen but I don't think we have any actions here.
