### ISSUE TITLE
Update to GitHub action actions/setup-python@v4 broke docs build

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#1134]
Lets debug and fix. 
- Example Fail: https://github.com/pypa/bandersnatch/runs/6871377009?check_suite_focus=true
- PR introducing fail: https://github.com/pypa/bandersnatch/pull/1132
  - I think it was missed as we don't always run doc_build unless certain files are changed ... Maybe we should add the docs yaml config too

**Comment by cooperlees** [comment]
Seems this has also broke our dependency vulnerability check: https://github.com/pypa/bandersnatch/runs/6874663934?check_suite_focus=true
- I think I'll roll back today until we workout what the issue is

**Comment by ichard26** [comment]
The problem is that version 4 doesn't have a default Python version. You have to specify the version either inline in the YAML or in a file.
