### ISSUE TITLE
Make finalize_sync optional when syncing packages

### ISSUE THREAD

**Issue by LeoQuote** [pypa/bandersnatch#1141]
When a package is already present in simple/index.html , it is uneccessary to update the simple/index.html , and the process is pretty time-consuming, especially when a non-filesystem storage backend is used.

**Comment by cooperlees** [comment]
So, this is done right - this is your `--skip-simple-root` option? Is there anything more here I'm missing?

**Comment by LeoQuote** [comment]
Exactly, I totally forgot it, closing as completed
