### ISSUE TITLE
Error dowload packages - bandersnatch 5.2.0

### ISSUE THREAD

**Issue by KhoiHUFI** [pypa/bandersnatch#1174]
I'm used python3.8 . help me

![image](https://user-images.githubusercontent.com/105619904/183390994-185e2a30-1a8b-4056-9784-b65c3574ffa0.png)

**Comment by cooperlees** [comment]
I'm going to say you're overloading your IO (disk / filesysttem) or network connection.

Please try lowering the `workers` in your bandersnatch config.
