### ISSUE TITLE
Add config values to set the log-output directory and debug on/off if bandersnatch.conf?

### ISSUE THREAD

**Issue by 89ao** [pypa/bandersnatch#1189]
Can we add a config to set the log-output directory and debug on/off ？
when I using docker ,it is not easy to change the command we use , instead , make  a configuration change is far more convient .

**Comment by cooperlees** [comment]
Log configuration can already be controlled by the logging modules `logging.config` https://docs.python.org/3/library/logging.config.html

- Code loading it: https://github.com/pypa/bandersnatch/blob/main/src/bandersnatch/main.py#L223
- Config file config in bandersnatch.conf:
https://github.com/pypa/bandersnatch/blob/main/src/bandersnatch/default.conf#L68

Does this not help you achieve what you want?

**Comment by 89ao** [comment]
thank you @cooperlees for your help，these two docs looks like very complexing to me.

May I have a simple example about how to config the file "/etc/bandersnatch-log.conf" ?

I simplely just want to collect every log and output to file like /var/log/bandersnatch.log

**Comment by 89ao** [comment]
update：
I've just write a config sample. Sharing to anyone who need it:
-----------bandersnatch.conf----------- 
log-config = /conf/bandersnatch-log.conf

-----------bandersnatch-log.conf-----------
[loggers]
keys=root,file
[handlers]
keys=root,file
[formatters]
keys=common
[logger_root]
level=NOTSET
handlers=root
[logger_file]
level=INFO
handlers=file
propagate=1
qualname=bandersnatch
[formatter_common]
format=%(asctime)s %(name)-12s: %(levelname)s %(message)s
[handler_root]
class=StreamHandler
level=DEBUG
formatter=common
args=(sys.stdout,)
[handler_file]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=common
delay=False
args=('/opt/bandersnatch/banderlogfile.log', 'D', 1, 0)

#class=handlers.RotatingFileHandler
#level=DEBUG
#formatter=common
#args=('/opt/bandersnatch/banderlogfile.log','D',1,'UTF-8')

**Comment by cooperlees** [comment]
Awesome. Thanks for sharing. PR welcome to add to bandersnatch docs if people feel it's worth it too. Closing for now.

**Comment by 89ao** [comment]
Thanks for your reminder , already did:
https://github.com/pypa/bandersnatch/pull/1280
