### ISSUE TITLE
Change from using pkg_resources to importlib.resource in Python 3.7

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#12]
Apparently faster etc. - In std library - lets see if it fits our use case and if so, lets use it.

PyCon 2018 talk on new module:
https://youtu.be/ZsGFU2qh73E

Can we please also ensure < 3.7 includes the backport so we can maintain Python >= 3.6 requirement for bandersnatch today please.

**Comment by opethe1st** [comment]
Working on this for the Bloomberg PyPA Sprint
