### ISSUE TITLE
Make CI pass in 3.11 + Docker build in 3.11

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#1314]
We do not pass in 3.11 ... Lets make it after latest packaging ...

Known issues:
- s3path: https://github.com/liormizr/s3path/issues/112

Once solved and integration tests pass lets change Docker to default to 3.11 too.

**Comment by cooperlees** [comment]
s3path needs 3.11 support: https://github.com/liormizr/s3path/issues/112

**Comment by cooperlees** [comment]
Gotta do Docker …

**Comment by ichard26** [comment]
With https://github.com/pypa/bandersnatch/pull/1341 landed, we can actually close this (I hope).
