### ISSUE TITLE
Will bandersnatch delete packages that are not on pypi.org but exist locally when synchronizing?

### ISSUE THREAD

**Issue by lxyeternal** [pypa/bandersnatch#1371]
All packages of pypi have been synchronized locally before. After a period of time, some package developers may have deleted them from pypi, but they are still kept locally. Whether these packages will be deleted when syncing again. If not, how to delete these packages in batches locally.

**Comment by cooperlees** [comment]
No. Only verify can cleanup packages. More information here: Lets discuss there: https://github.com/pypa/bandersnatch/issues/1273 ...
