### ISSUE TITLE
Add package serial to generated Simple HTML

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#141]
PyPi.org / Warehouse adds the package Serial into the generated HTML as a comment. We should do the same.

The serial can be found in the JSON  we use to find package files etc.
```
{"info": {"last_serial": XXXX}}
```
HTML
```
</html>
<!--SERIAL 696969-->
```

We should pass that into the html generation function and add it into the HTML.

**Comment by rene-d** [comment]
"last_serial" is outside the "info" block - I hope this won't change ;-)
I wrote a modification -> PR

**Comment by cooperlees** [comment]
Hmmm - good point re changing ... PyPI try not to change things with this API much.
- Maybe we should catch KeyError and LOG if it fails so we don't fail a sync run if this breaks?

**Comment by rene-d** [comment]
I hesitated a long time to get 'last_serial' (and 'info') only if it is in the metadata - so I wouldn't have to review all the tests ;-) And I have noticed that you pass the name of the 'releases' entry as a parameter of the `verify()` function.

I cannot know if we can rely on the content of the JSON data. Or if people use bandersnatch with other mirrors than https://pypy.org.

**Comment by cooperlees** [comment]
bandersnatch's main goal is only mirroring from pypi.org. There is not enough metadata to fill from another mirror. We could hit pypi.org for meta data and have as second "static_mirror" defined in the config and use that to pull the data / package / module files (sdists, whls etc.) - But that does not exist today.

**Comment by cooperlees** [comment]
This is done. Missed closing this.
