### ISSUE TITLE
Improve mirror filtering for latest releases

### ISSUE THREAD

**Issue by kefir-** [pypa/bandersnatch#1433]
As described in the docs, bandersnatch can filter mirror to only include the latest releases:

https://bandersnatch.readthedocs.io/en/latest/filtering_configuration.html#keep-only-latest-releases

But this can introduces some problems, and I think it boils down to a definition of what exactly the latest releases are. Currently, bandersnatch appears to sort all releases by version number:

https://github.com/pypa/bandersnatch/blob/main/src/bandersnatch_filter_plugins/latest_name.py#L52

and then it selects the versions to keep. But this is a problem, because there may be two major releases under maintenance, and if you don't fetch everything you might miss security fixes for the old major release. For example, if the chronological release order looks like this:

1.0.0
1.1.0
1.2.0
1.3.0
1.3.1
1.3.2
2.0.0
2.0.1
1.3.3
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.0.7
1.3.4 critical patch
2.0.8
2.0.9

If keep is set to 10 and we run bandersnatch, then v1.3.4 will not be fetched, even if it was released yesterday. So instead of sorting by version numbers, it might make sense to instead keep the latest 10 versions listed under Release history, eg https://pypi.org/project/bandersnatch/#history or https://pypi.org/rss/project/bandersnatch/releases.xml. 

Also, a more sensible setting might be to add a different option to fetch all updates from the last X days/months (falling back to the latest release if it was even older). This seems less arbitrary than a release version count of for example 20, which could be 20 releases that are all 10 years old for one project, and 20 releases within only the last week for another project.

**Comment by cooperlees** [comment]
A PR is welcome to add a configurable "chronological" latest releases addition to the plugin. I'll only accept it configurable and with unittests added showing how this works with documentation showing how to use and stating how it differs.

bandersnatch uses the "JSON" and "simple" APIs from PyPI to get metadata today. I guess you'll have to use the `upload_time_iso_8601` of each release to find the last X chronological versions. I don't think we need to pull in the XML as well to do this. I'd like to avoid adding more HTTPS calls.

Thanks!
