### ISSUE TITLE
Bandersnatch mirror do not mirror the dependencies for the packages mentioned on allow list ?

### ISSUE THREAD

**Issue by goyalgagan** [pypa/bandersnatch#1472]
Hi ,
We have implemented the Private Pypi mirror setup using bandersnatch .
We have used the allowlist to allow few package and those are getting mirrored successfully.

But when I try to install it using pip from mirror , it fails as don't find the dependencies there.

is there a way allow list can mirror the all dependent packages as well so it can work just like public pypi ?

This issue is going to beat entire purpose of setting up private pypi.

**Comment by cooperlees** [comment]
Howdy there. bandersnatch does not implement dependency resolving. Please use pip to install all the modules you want into a venv (virtual environment) and use "pip freeze" to get a list of packages you want in your allow list. I would happily take a PR to document this somewhere.

There are to many cans of worms if bandersnatch was to introduce dependency resolving ... I'm a big believer in the UNIX principle here and we just want to mirror what we're told well. But I am open to discussion, but would need more maintainers if we did want to add this feature.

**Comment by cooperlees** [comment]
Please reopen if you want to do more here - e.g. documentation about dependency solving ...
