### ISSUE TITLE
Case Sensitivity Issue

### ISSUE THREAD

**Issue by bpfeffer** [pypa/bandersnatch#159]
I have created a full mirror of PyPi using Bandersnatch to use on my air-gapped systems, this is typically very effective but I ran into an interesting issue today. 

Pip is case-insensitive, so if I tell it I want to install the package InSilicoSeq, instead of looking for web/simple/InSilicoSeq it automatically looks for web/simple/insilicoseq. 

The mirroring of Bandersnatch retains the case in the package folders in "simple" and that is breaking things. In the example above, the URLs from pypi.org are automatically lowercase(in the above example, https://pypi.org/simple/insilicoseq/ vs https://pypi.org/project/InSilicoSeq/).

Can you please do something to resolve this to reflect the case-insensitive nature of the packages on PyPi?

**Comment by cooperlees** [comment]
Hi,

Thanks for the report. Bandersntach *should* write out both the author's chosen case + the [PEP 503 normalized](https://www.python.org/dev/peps/pep-0503/#normalized-names) version. Bandersnatch does this so we can allow mirror to be a static representation of PyPI. You should have:
- https://awesome.mirror/simple/insilicoseq/
- https://awesome.mirror/simple/InSilicoSeq/

I checked one of my mirrors and it indeed does have both as I explained above. `pip` also works as expected with the package you're having issues with:
```
cooper-mbp:tmp cooper$ /tmp/test_bs/bin/pip -V
pip 19.0.3 from /private/tmp/test_bs/lib/python3.7/site-packages/pip (python 3.7)
cooper-mbp:tmp cooper$ /tmp/test_bs/bin/pip download -i https://pypi.facebook.com/simple/ insilicoseq
Looking in indexes: https://pypi.facebook.com/simple/
Collecting insilicoseq
  Downloading https://pypi.facebook.com/packages/78/10/cb16af1844ca8d5d6a8a7f631244d7b7d0748ed8158c6df3cfafdae6d51a/InSilicoSeq-1.3.3-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 4.7MB/s
  Saved ./InSilicoSeq-1.3.3-py3-none-any.whl
Collecting pysam>=0.15.1 (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/15/f6/ce0611aaa1865a616f7dc164fbf046eaf38f2b17c6d404403c56250beb93/pysam-0.15.2.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 398kB/s
  Saved ./pysam-0.15.2.tar.gz
Collecting scipy (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/dd/6c/ccf7403d14f0ab0f20ce611696921f204f4ffce99a4fd383c892a6a7e9eb/scipy-1.2.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.3MB)
    100% |████████████████████████████████| 27.3MB 1.0MB/s
  Saved ./scipy-1.2.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting joblib (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl (278kB)
    100% |████████████████████████████████| 286kB 5.7MB/s
  Saved ./joblib-0.13.2-py2.py3-none-any.whl
Collecting requests (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 1.8MB/s
  Saved ./requests-2.21.0-py2.py3-none-any.whl
Collecting future (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 143kB/s
  Saved ./future-0.17.1.tar.gz
Collecting biopython (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/f0/6f/388e730f61ca76dbc89885e102d6105124151c3291e8ac0a08be51410afd/biopython-1.73-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 4.8MB/s
  Saved ./biopython-1.73-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy (from insilicoseq)
  Downloading https://pypi.facebook.com/packages/46/e4/4a0cc770e4bfb34b4e10843805fef67b9a94027e59162a586c776f35c5bb/numpy-1.16.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 555kB/s
  Saved ./numpy-1.16.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->insilicoseq)
  Downloading https://pypi.facebook.com/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 9.7MB/s
  Saved ./urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->insilicoseq)
  Downloading https://pypi.facebook.com/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 2.9MB/s
  Saved ./idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->insilicoseq)
  Downloading https://pypi.facebook.com/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 8.8MB/s
  Saved ./certifi-2018.11.29-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->insilicoseq)
  Downloading https://pypi.facebook.com/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 7.7MB/s
  Saved ./chardet-3.0.4-py2.py3-none-any.whl
Successfully downloaded insilicoseq pysam scipy joblib requests future biopython numpy urllib3 idna certifi chardet
```

What version of `Python` and `pip` are you using? Can you please share the command and the failure output. I need a repro in order to try and fix.

**Comment by bpfeffer** [comment]
I'm seeing that this is probably related to an issue on my end. I have been using VMware on my Windows system to run a CentOS6 VM and do create the mirror, and my CentOS VM does not like my encrypted drive connecting directly so I've had to use VMware as a bridge to mount the drive; this introduces some issues, including a lack of case-sensitivity. 

Sorry for the confusion, I wasn't aware that it was trying to get both case-versions for the packages that weren't originally lowercase. Until I can find a way to mount my drive properly to the VM, case-sensitivity will be an ongoing issue for me, along with long filenames(though I did enable long paths). I'm surprised that it has taken months of using the mirror for this issue to crop up, 

Does Bandersnatch download everything that has capital letters twice, to produce a lowercase and original-case version? Could you possibly add a feature to just get the lowercase version? I will just have to convert my existing copy to all lowercase,

**Comment by cooperlees** [comment]
Awesome. Ok, glad you worked it out. Eventually (prob 2020 when Py2 dies) I'll remove writing out both index.html files.

I am open to the configuration option. Please submit a PR. It will be low priority for me as many people will not need this. The code change itself wouldn't be very large, you could just gate based on the config bool to write out the non normalized directory name.

I am going to close the issue. Feel free to reopen if you want to do the PR and discuss. Or just put the PR up.
