### ISSUE TITLE
Latest x releases: version sorting broken

### ISSUE THREAD

**Issue by miicha** [pypa/bandersnatch#1593]
For some packages the version sorting of the x last relases does not work which leads to not fetching any versions.

This is caused by a problem of the version parsing in `packaging.version`. It usually works but the regex does not match arbitrary letters. 
The problem was observed in the `pytz` package: versions 2004a, 2004b, 2004b.2 are pased correctly but 2004d raises an error. 
Additionally the filtering is done in a large `try ... except` block that silently ignores the error in the `on_error` function which made debugging necessary.
```
        elif isinstance(exception, TypeError) or isinstance(exception, ValueError):
            # This occurs for testing or when todolist is corrupt
            pass
```

The problem could be mitigated by implementing #1433.

**Comment by cooperlees** [comment]
I don't believe that is PEP440 valid versioning, so due to that I don't expect bandersnatch to support it cleanly.

**Comment by miicha** [comment]
That is very likely. Nevertheless, it is a blocking issue for me to setup a mirror, because there are ~20 required packages that are not downloaded due to this issue (and stay on the todo list). For me the `sort_by = time` would be sufficient, so feel free to close this entry after merging PR https://github.com/pypa/bandersnatch/pull/1594.

**Comment by cooperlees** [comment]
Won't support outside PEP440 ...
