### ISSUE TITLE
Problems creating symlinks on Windows 10

### ISSUE THREAD

**Issue by flyinghyrax** [pypa/bandersnatch#1688]
I have started to see test failures related to symlinks not being created correctly on my Windows workstation. I wasn't seeing these Q1 of this year. Initial searching around StackOverflow etc. indicates this is likely not universal and might be a setting that got toggled/reset during a feature update. If that's the case maybe it's something worth documenting as a platform-specific limitation.

I've dumped version and error information in here regardless for anyone having a similar problem.

**UPDATE** - this is a documented limitation that I've just _somehow never encountered before_.

There is a note in the docs for `os.symlink` here: <https://docs.python.org/3.12/library/os.html#os.symlink>

A detailed comment on the Windows permissions involved: <https://stackoverflow.com/a/32878688>

Looks like a recent update just reset some things on my system - the restriction on symlinks isn't new / wasn't added by a recent update.

Leaving logs of failed tests below to make this easier to find for anyone else who encounters the same problem. (`OSError: [WinError 1314] A required privilege is not held by the client`)

--------------------------------------

The following unit tests all have similar failures:

- `tests/test_mirror.py` - symlink error is in captured log output
    - `::test_keep_index_versions_stores_one_prior_version`
    - `::test_keep_index_versions_stores_different_prior_versions`
    - `::test_keep_index_versions_removes_old_versions`
- `tests/test_verify.py` - symlink error during setup of `FakeMirror` test object
    - `::test_verify_producer`
    - `::test_fake_mirror`
    - `::test_delete_unowned_files`
- `tests/plugins/test_storage_plugins.py` - error in calls to `self.plugin.symlink`
    - `::TestFilesystemStoragePlugin::test_scandir`
    - `::TestFilesystemStoragePlugin::test_symlink`

Representative exception output from pytest:

```
__________________ TestFilesystemStoragePlugin.test_symlink ___________________

self = <test_storage_plugins.TestFilesystemStoragePlugin testMethod=test_symlink>

    def test_symlink(self) -> None:
        file_content = "this is some text"
        test_path = self.plugin.PATH_BACKEND(self.mirror_base_path).joinpath(
            "symlink_file.txt"
        )
        test_path.write_text(file_content)
        symlink_dest = test_path.parent.joinpath("symlink_dest.txt")
>       self.plugin.symlink(test_path, symlink_dest)

src\bandersnatch\tests\plugins\test_storage_plugins.py:919: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src\bandersnatch\storage.py:291: in symlink
    dest.symlink_to(source)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = WindowsPath('C:/Users/mrsei/AppData/Local/Temp/tmpex3j7mad/srv/pypi/symlink_dest.txt')
target = WindowsPath('C:/Users/mrsei/AppData/Local/Temp/tmpex3j7mad/srv/pypi/symlink_file.txt')
target_is_directory = False

    def symlink_to(self, target, target_is_directory=False):
        """
        Make this path a symlink pointing to the target path.
        Note the order of arguments (link, target) is the reverse of os.symlink.
        """
        if not hasattr(os, "symlink"):
            raise NotImplementedError("os.symlink() not available on this system")
>       os.symlink(target, self, target_is_directory)
E       OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\mrsei\\AppData\\Local\\Temp\\tmpex3j7mad\\srv\\pypi\\symlink_file.txt' -> 'C:\\Users\\mrsei\\AppData\\Local\\Temp\\tmpex3j7mad\\srv\\pypi\\symlink_dest.txt'
```

> These hash checking tests are also failing at assertion time but aren't logging an `OSError` - could be related, or not:
> - `tests/plugins/test_storage_plugins.py::TestFilesystemStoragePlugin::test_get_hash`
> - `tests/plugins/test_storage_plugins.py::TestFilesystemStoragePlugin::test_hash_file`

Representative error from integration test logs:

```
2024-03-20 12:36:17,917 ERROR: Error syncing package: acmplus@5103287 (mirror.py:378)
Traceback (most recent call last):
  File "C:\Users\mrsei\source\bandersnatch\src\bandersnatch\mirror.py", line 131, in package_syncer
    await self.process_package(package)
  File "C:\Users\mrsei\source\bandersnatch\src\bandersnatch\mirror.py", line 340, in process_package
    await loop.run_in_executor(
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrsei\source\bandersnatch\src\bandersnatch\mirror.py", line 709, in sync_simple_pages
    self._save_simple_page_version(package, simple_pages_content)
  File "C:\Users\mrsei\source\bandersnatch\src\bandersnatch\mirror.py", line 769, in _save_simple_page_version
    symlink_path.symlink_to(full_version_path)
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\mrsei\\AppData\\Local\\Temp\\pypi\\web\\simple\\a\\acmplus\\versions\\index_5103287_2024-03-20T163617.917470Z.html' -> 'C:\\Users\\mrsei\\AppData\\Local\\Temp\\pypi\\web\\simple\\a\\acmplus\\index.html'
```

**Comment by cooperlees** [comment]
So a permission fix helps this work again? So there is no workaround / logic change bandersnatch needs?

**Comment by flyinghyrax** [comment]
Correct. In newer versions of Windows 10, a regular user does not have permission to create symlinks, unless:

- They are an administrator and use an elevated terminal
- Developer Mode is enabled

I had developer mode enabled and had never encountered this problem previously. A recent update disabled Developer Mode - I had to go into settings and re-enable it.

**Comment by flyinghyrax** [comment]
If we wanted to work around the limitation, we could try to check for the permission somehow, and/or use junctions for directories on Windows since those don't seem to need the same permission. Seems like a lot of platform specific complexity, but I don't know how common it is for end users to run bandersnatch on Windows.
