### ISSUE TITLE
os.uname not supported on Windows

### ISSUE THREAD

**Issue by lordyavin** [pypa/bandersnatch#19]
I just tried to setup bandersnatch on a windows host and got an error because os.uname() ist not supported. Either switch to platform.uname() or document in the README that Windows isn't supported as a host.

> (bandersnatch) C:\Users\john\software\bandersnatch>bandersnatch mirror
> Traceback (most recent call last):
>   File "C:\Users\john\software\Python36-32\Lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\john\software\Python36-32\Lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\john\software\bandersnatch\Scripts\bandersnatch.exe\__main__.py", line 5, in <module>
>   File "c:\users\john\software\bandersnatch\lib\site-packages\bandersnatch\main.py", line 3, in <module>
>     import bandersnatch.master
>   File "c:\users\john\software\bandersnatch\lib\site-packages\bandersnatch\master.py", line 1, in <module>
>     from .utils import USER_AGENT
>   File "c:\users\john\software\bandersnatch\lib\site-packages\bandersnatch\utils.py", line 23, in <module>
>     USER_AGENT = user_agent()
>   File "c:\users\john\software\bandersnatch\lib\site-packages\bandersnatch\utils.py", line 12, in user_agent
>     system = os.uname()
> AttributeError: module 'os' has no attribute 'uname'

**Comment by cooperlees** [comment]
Thanks for the report - I have no problem fixing this and I apologize! PR welcome or I will try get to it asap.

**Comment by cooperlees** [comment]
Please also let me know if there is any pathing / directory issues as well.

- We should probably also try and run the unit tests on Windows. I have never bothered as I have not heard of users. Also welcome PRs adding this :)

**Comment by lordyavin** [comment]
So far no path issues.

**Comment by cooperlees** [comment]
3.0.0 will be the first "best effort windows supported" release.

We will try and get some Windows CI runs happening somehow. (None of use are Windows users). We will welcome help :D
