### ISSUE TITLE
3.3.0 Platform Filter Plugin Noise when not enabled

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#195]
Need this supressed if the plugin is not asked to be enabled.
```
[2019-04-12 12:59:35,719] INFO: Plugin exclude_platform: missing platforms= setting (filename_name.py:27)
```
- I think this is common across all plugins

cc: @rene-d

**Comment by rene-d** [comment]
Hi,

Yes, I will suppress this message. I guess the plugin is enabled with "all" keyword in plugins= setting.

**Comment by cooperlees** [comment]
I'll also look into it. I feel the plugins all need to be a little smarter.
