### ISSUE TITLE
3.3.0 Latest releases plugin could remove "official" version

### ISSUE THREAD

**Issue by rene-d** [pypa/bandersnatch#196]
In some cases (about 2500...), the most recent releases are not the official (or stable?) one referenced in the "info" section of the JSON.

I'm writing a fix.

**Comment by rene-d** [comment]
BTW, I think the `verify` command will download the whole mirror, despite this filter (and platform one). I'll check and propose a fix too.

**Comment by cooperlees** [comment]
Yes, verify has never been made plugin respectful. Should probably open a separate issue for that.

Verify is all async and I want to one day (once xmlrpc is dead) refactor main bandersnatch to be fully async too.

**Comment by rene-d** [comment]
Well, PR submitted.

I'm still circumspect about this feature (keeping the last release)... However, I was able to reinstall all my favorite packages only with the reduced mirror. And its size is divided by 12.
