### ISSUE TITLE
Generate data-requires-python attributes in index.html does not work for all packages

### ISSUE THREAD

**Issue by konetzed** [pypa/bandersnatch#201]
Bandersnatch 3.3.0 

I have run bandersnatch mirror --force-check to verify everything was correct.  I have noticed that some of the pages have the data-requires-python such as `gallery-dl` but `more-itertools` does not.  

One major difference I have noticed between these two packages is `gallary-dl` has the option set on all packages where `more-itertools` only has it set on some.

more-itertools links
https://pypi.org/simple/more-itertools/

gallery-dl links
view-source:https://pypi.org/simple/gallery-dl/

Files from my mirror

[gallery-dl.html.txt](https://github.com/pypa/bandersnatch/files/3081251/gallery-dl.html.txt)
[gallery-dl.json.txt](https://github.com/pypa/bandersnatch/files/3081253/gallery-dl.json.txt)
[itertools.html.txt](https://github.com/pypa/bandersnatch/files/3081254/itertools.html.txt)
[more-itertools.json.txt](https://github.com/pypa/bandersnatch/files/3081255/more-itertools.json.txt)

bandersnatch.conf JIC I dont have my options correct.
[bandersnatch.conf.txt](https://github.com/pypa/bandersnatch/files/3081263/bandersnatch.conf.txt)

Willing to help test or debug more.  I just don't know what else would be helpful.

**Comment by konetzed** [comment]
You can close this.  I figured out how to create a small subset mirror with just `more-itertools` and `gallery-dl` and the pages were generated correctly.  Not sure why my mirror isn't updating right.

**Comment by cooperlees** [comment]
Ok - glad it worked out!
