### ISSUE TITLE
Add plugin support for flitering package files

### ISSUE THREAD

**Issue by dwighthubbard** [pypa/bandersnatch#212]
I'd like to be able to filter the package files being downloaded.  For maximum flexibility I envision this as being implemented as 2 more types of filtering plugins.

1. Filter the package by name, this would allow implementing filter modules that prevent the download of package files based on the filename.  I.E blacklist/whitelist/regex filter plugins.

2. Filter the package by contents, this would allow implementing filters that can evalutate the package contents prior to adding it to the index.

The one tricky issue with this implementation is how should the json metadata be handled.  Currently it is a copy of the metadata from the upstream servers.  The question is should these plugins remove the unmirrored packages from the json data and how to persist the changes.

**Comment by cooperlees** [comment]
@dwighthubbard - Did you complete all this @ PyCon?
