### ISSUE TITLE
README fix: link to PyPI API

### ISSUE THREAD

**Issue by brainwane** [pypa/bandersnatch#217]
In the bandersnatch README at https://github.com/pypa/bandersnatch/blob/master/README.md , please improve the line:

> An example of an unsupported API is PyPI's XML-RPC interface, which is used when running `pip search`.

by adding a link to https://warehouse.readthedocs.io/api-reference/xml-rpc/ .

**Comment by vinayak-mehta** [comment]
Submitted a PR for this!
