### ISSUE TITLE
global filter for minimal python version and architecture

### ISSUE THREAD

**Issue by panzerballett** [pypa/bandersnatch#223]
(feature request)

as the PyPI mirror is rapidly growing it would be nice to be able to filter for a minimal python version and exclude unwanted architectures. i admit that this defeats the purpose of creating a full python mirror; but would perfectly fit my use-case...

seeing that a package has files of the form

```
{package}-{version}
  .tar.gz
  -cp37-none-win_amd64.whl
  -cp35-cp35m-manylinux1_x86_64.whl
  -cp36m-manylinux1_i686.whl
  -cp36-cp36m-win_amd64.whl
  -cp27-cp27m-manylinux1_x86_64.whl
  -cp36-cp36m-macosx_10_7_x86_64.whl
  -cp35-cp35m-win_amd64.whl
  -...
```

i would like to be able to have a global filter that e.g. only considers packages for `python>=3.5` and exclude builds for `macosx` and `win`; something of the form (that is probably not even valid syntax...):

```
[global_filter]
python_version = 
  >=3.5
arch =
  + manylinux1
  - macosx
  - win
```

or is that already possible and i missed it? or is it something that can not be done?

**Comment by rene-d** [comment]
Hi, you can already filter by platforms (see [here](https://github.com/pypa/bandersnatch/blob/master/docs/filtering_configuration.md#platform-specific-binaries-filtering)).

Removing specific versions of Python is not an easy task because of the naming differences of the distribution files.

**Comment by panzerballett** [comment]
oh, how could i have missed this?! thanks!

**Comment by cooperlees** [comment]
I feel we could add a plugin to look at Python Requeires in the JSON (json["info"]["requires_python"]) BUT, a lot of projects don't define this. So you might end up with a **VERY** incomplete mirror

**Comment by panzerballett** [comment]
thanks a lot for your reply!

now that filtering architectures has been pointed out to me (yes, i feel stupid!) i think my use-case is more than covered.

sorry to have bothered - and feel free to close the issue. and: thanks for such a great tool!

**Comment by cooperlees** [comment]
I'd rather you ask and use bandersnatch then give up. Please continue to ask. If you hit any bug lets us know! Thanks.
