### ISSUE TITLE
JSON duplication and PEP 566

### ISSUE THREAD

**Issue by electricworry** [pypa/bandersnatch#287]
Because PyPI enforces PEP 566, a project name can be "Hello-World", "hello_world", and "hELLo-WORLD" at different points in time.

This can cause bandersnatch to end up with multiple JSON files all representing the same project. When "mirror" is run, updates since previous serial will be reported and will use project names that might differ to previous capitalisation, thereby introducing duplicates. A "verify --json-update" will cause the JSON with old project name to be updated (it works because PyPI will redirect to the new name, and bandersnatch follows the redirect) but it will not rename the file with the new name.

These JSON file duplicates are benign, but they cause issues if (like I do) you are importing them all into an offline copy of warehouse; in which case they will cause a PEP 566 key clash.

It's debatable whether bandersnatch should avoid this problem or if the importer should handle the problem. However in my environment, I've decided to modify behaviour of "verify --json-update". In my copy, I've modified _get_latest_json() to interrogate the value of info/name after update and rename if required. (An alternative would be to turn off redirection when doing url_fetch so that mismatches were deleted; I decided that that was decidedly unsafe since redirects could be used in the future to migrate to a new path specification.)

Any thoughts about whether this counts as a problem and I can contribute a fix, or whether it should be dismissed as not an issue?

Thanks.

**Comment by cooperlees** [comment]
#52 + #120 talk about parts of this issue. I'd love to get fixes in for them.

In 4.0 I want to move bandersnatch to only mirror the Normalized name for the Simple API and JSON. This is an option now as `pip` now always defaults to looking for the normalized name first (I believe and will double check before attempting to implement). I've talked about parts of this in #138.

I feel, since `verify` is a 'newer' bandersnatch option we should just make it only care about the normalized name only (for deletion and when crawling JSON for verifying). I feel this is basically what you've done? (Or have I misunderstood?)

More detail:
- When crawling, only care about JSON files who's name == normalized_name
- When deleting - Only care about deleting the normalized name file

Then in 4.0 we should stay clean. I would also provide a utility script to cleanup before 4.0 mirrors to remove the non needed JSON.

**Comment by electricworry** [comment]
If I understand correctly, normalised would mean PEP 503, where all characters are lowercase, and runs of "-_." characters are replaced with "-":

`re.sub(r"[-_.]+", "-", name).lower()`

(I can see why this is fine; the package https://pypi.org/project/0-._.-._.-._.-._.-._.-._.-0/ can be accessed as https://pypi.org/project/0-0/)

This could get a bit messy; I'm not sure how to best approach, so I'll take your guidance. As a user I don't really get the pre-4.0/post-4.0 delineation, as I just want clean mirrors, and it's been a bit of an iterative process getting there. :)

Here's various use cases, and what I think should happen, and I'd welcome your input as to what needs changed.

1. Running an initial mirror with 4.0 release. In this case, we will be using normalised names. Master will report non-normalised names, but we will normalise them anyway; so we store the JSON files and links in normalised form, and we query master for the normalised name, which it is fine with.
2. Running a mirror update with 4.0 release, against 4.0 data. In this case existing data is normalised, and we convert package names to normalised form when master reports updates. This is also fine.
3. Running a mirror verify with the 4.0 release, against 4.0 data. Here we already start with normalised names from the JSON files, and we are either updating or deleting those files. Fine.

Now for older mirrors...

4. Running a mirror update with the 4.0 release, against pre-4.0 data. In this case we will be converting the names reported by master to normalised form. However, there will be non-normalised files in the mirror already. This will create duplicates (e.g. "0-._.-._.-._.-._.-._.-._.-0" and "0-0"). That's acceptable, and a 'cleanup' will be required to fix that.

I propose that the cleanup is done as part of the verify use case:

4. Running a verify with 4.0 release, against pre-4.0 data. Here we've got a mix of normalised and non-normalised names of JSON files. For each file, if the name is not normalised and the normalised name doesn't already exist, then rename it to the normalised name (and also delete and recreate the symbolic link). If the name is not normalised, and the normalised name already exists, then there's a clash; keep the newer one, leaving it and symlink with normalised name. The verify can now proceed as normal (in all permutations of --delete and --json-updates); the names are now all normalised and there will be no duplicate keys.

I think if that's what we do, you can transition to your goal of normalised name storage, elegantly handle old non-normalised names, and also avoid having a new switch or utility to get there (transparent to the user is better I think).

Thoughts?

**Comment by cooperlees** [comment]
To confirm, When I say `4.0`, I mean 4.0 for bandersnatch where I'll break some backwards compatibility. It seems you understood that.

1-3 ... Sounds totally reasonable.

4: Totally agree with verify being able to fix this. Happy for you to add a transparent fix for this into verify.

All PRs here sound awesome and will be accepted :)
- We just need to test that `pip` works with some of these "funky" non normalized names once we noramlize all the 

Happy to accept and merge into a 3.5.x release too, we will just have to config gate it until it becomes default in 4.0. Thanks for being verbose and explaining. Have assigned for you for now!

**Comment by electricworry** [comment]
After a long hiatus I'm looking at this again. Apologies for the rude period of silence. I'll be looking at this minor problem over the next few week as I've got to redesign some mirrors at work.

I was wondering, can anyone tell me what the current size of a complete PyPI mirror is at the moment without denylists?

**Comment by cooperlees** [comment]
Yes, PyPI.org can. It’s 6.7T.
- https://pypi.org/stats/

Denylisting (new terms around here now) can cut that down just filtering the top 20 packages in that list too.

**Comment by electricworry** [comment]
Thank you very much! I wasn't aware of that page's existence.

**Comment by electricworry** [comment]
I've taken a look at this on the current codebase and I think it might be moot now. Changes - such as a1911a5 - ensure that a PEP 503 normalized name is used for project names (in both json and index filenames). I've done some testing with a fake project and I've done some abuse of the name, and both mirror and verify features consistently store only the PEP 503 name, so I can't reproduce the behaviour I used to experience.

It's possible for people with mirrors that were started pre-4.0 will have some lingering misnamed files, but it's not going to be a problem for most, and if they really want or need to do a cleanup then they might want to just delete their local json files and indexes and run "bandersnatch mirror --force-check && bandersnatch verify" which will ensure all indexes are pristine and correct and prune orphaned files.

Thoughts?

**Comment by cooperlees** [comment]
Yup, this would have been a side effect from my ensuring we only sync the normalized name now since 4.0. Nice. I guess we can close this.

If anyone one hits this, to cleanup, all it would take would be to write a very simple utility to go through a base JSON (and simple) directory and if a directory is not == to a normalized name, recursively delete it.

Thanks for testing!
