### ISSUE TITLE
Filtered Packages Not Being Removed

### ISSUE THREAD

**Issue by daheise** [pypa/bandersnatch#307]
We are running a PyPI mirror with bandersnatch and have recently enabled a number of filters.
One goal of our filtering is to reduce the mirror size. However, after enabling the filters,
no packages seem to get deleted. How do we go about getting packages cleaned off of the mirror
that do not meet our filtering configuration? Does only the verify command delete packages?

Our config file looks similar to this:

```
[mirror]
directory = /srv/pypi
json = true

master = https://pypi.org/

timeout = 10

workers = 3

hash-index = false

stop-on-error = false

delete-packages = true
verifiers = 2

[plugins]
enabled =
    latest_release
    blacklist_project
    regex_project

[blacklist]
packages =
    example1

[filter_regex]
packages =
    .+-evil$

[latest_release]
keep = 3
```

**Comment by cooperlees** [comment]
Hi,

Verify is the only operation that deletes packages that have been removed upstream. I like this feature as one reason some people mirror is to protect from upstream deletions.

Plugins also only work during syncing and will not go back and cleanup your mirror. Also, ‘verify’ does not respect plugins. It looks at syncing packages that JSON you have saved, and will go and grab all releases of said package.

Open to ideas here, but I’d like to not over complicate bandersnatch. Most people here just take the wasteful route, delete their mirror and re-download with the plugins on or manually cleanup.

**Comment by cooperlees** [comment]
What you should try is to delete the ‘status’ file in the root of the mirror dir and force a full sync and see what happens.

Also, what version are you running?

**Comment by daheise** [comment]
With the latter strategy, how is `latest_release` intended to function? It seems like as new releases come out, one would quickly exceed whatever limit one thought they had set. Is that the case, and the recovery method is simply to re-do the mirror?

We're on version 3.4.0

**Comment by daheise** [comment]
We can try deleting the status file and report back; if I recall correctly that will take us a few days to run.

**Comment by daheise** [comment]
For the record, my expectation as a user is that if I have `delete-packages = true`, then bandersnatch would delete packages that fail to pass the filter. Given the way `todo` and `status` works, only applying filters when encountering a change is slightly surprising, but understandable.

**Comment by cooperlees** [comment]
The sync will be a lot quicker this time as you will be only downloading the JSON metadata, stating and deleting files.

Deletion broke long ago and I opened an issue before I was a maintainer. I invented verify to fill the void. Maybe I missed the config option, and we should just remove it all to avoid confusion.

Documentation PRs welcome and suggestions on how you think we could improve this.

**Comment by daheise** [comment]
Deleting the status file did not cause the `keep_release` or `filter_regex` plugins to trigger deletes. We wouldn't expect the `blacklist` to in our configuration at the moment; we'll add a canary to test it.

We do see that `filter_regex` is correctly skipping packages that match.

**Comment by daheise** [comment]
Would you be interested in a PR that will delete packages that don't make it through the filters? It would be protected by a configuration option, of course. I'd like to have this happen at mirror time, rather than verify time; verify operations take quite a while. Perhaps a new command like 'purge' for deleting stale data that doesn't meet the filters.

I see two places one could apply removals: Delete the packages removed from [`packages_to_sync`](https://github.com/pypa/bandersnatch/blob/01101aea28db0b9cdceb8d660e5ffc1e722e46ad/src/bandersnatch/mirror.py#L206) when filtering. And the diff on [`Package.self.releases`](https://github.com/pypa/bandersnatch/blob/01101aea28db0b9cdceb8d660e5ffc1e722e46ad/src/bandersnatch/package.py#L126) before and after filtering. 

In the case of a differential mirror (one serial to another) this operation would only affect updated packages. If you remove the status file, then you would clean the entire local mirror based on the current filters.

I can't commit to making the PR, but I'd like to know if there's interest before I sink much time into an effort.

**Comment by cooperlees** [comment]
So I added a delete. But I would be open to accepting your pr to check and delete packages that match filters during a sync run. And yes, please make it enabled via config to start. We could look at making it the default in 4.0 ...

I feel the code might need some refactoring to allow clean implementation tho.

**Comment by NateDreier** [comment]
Just out of curiosity, was this ever resolve?

I have the same issue - Pypi has become to big so adding filters to shrink it down and realizing now that it cannot be done retroactively.

**Comment by cooperlees** [comment]
No, bandersnatch can not retroactively go and cleanup based on newly set filters. To do this sanely we'd either need to add state (which I've always tried to avoid) or walk the filesystem (like verify does today) to know what you have on diskl.

I would take a PR that added this ability to mirror and/or verify. But I feel the change would be so core you would need to change a lot.

**Comment by cooperlees** [comment]
Please reopen if anyone ever wants to do this large undertaking.
