### ISSUE TITLE
What’s the pypi release schedule?

### ISSUE THREAD

**Issue by artagel** [pypa/bandersnatch#317]

**Comment by artagel** [comment]
Just curious, how often does the project update to pypi, and what’s the trigger?

**Comment by cooperlees** [comment]
There is no schedule. Just when a new feature or bug fix happens I push. I’m a solo maintainer. I’ll look at getting your feature out today, so I guess you can get rid of your local fork :)

Thanks for the new feature!

**Comment by artagel** [comment]
Thanks for being the sole maintainer!  And thanks for working the pr so quickly.

**Comment by cooperlees** [comment]
https://pypi.org/project/bandersnatch/3.5.0/ is out.
