### ISSUE TITLE
Fix `Any` typing for argparse.ArgumentParser in main.py

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#325]
Line 20 we're using `Any` as mypy was complaining that argparse.ArgumentParser does not have a `add_parser` method.

**Comment by sukhbeersingh** [comment]
Hi, I did some research on the argparser package and found that we could use the `argparse._SubParsersAction` type instead of `Any`. I ran tox locally and everything seems fine.

Please let me know if this is okay.
