### ISSUE TITLE
`__main__`

### ISSUE THREAD

**Issue by jayvdb** [pypa/bandersnatch#383]
It would be nice to have a `__main__` so the CLI can be accessed without using `pkg_resources`

**Comment by cooperlees** [comment]
Hello. Can you please be a little more verbose on your exact need here please. 

I'm guessing you want to be able to run bandersnatch without installing it? This would break all plugins. If plugins are not needed, this could be made to work. I would feel this would need a lot of import fixing, but even if we did do this how are you going to install dependencies?

Or is it `configuration.py` using it to try and find the default configuration? That we could remove easily.

**Comment by jayvdb** [comment]
I am wanting to run installed bandersnatch as a CLI, with all plugins, from within PyOxidizer.  `pkg_resoures` doesnt work for programs added inside the 'oxidized' runtime, but works fine for loading plugins outside of the embedded runtime.  `__main__` is a more stable interface than getting the entry point out of installed dist-info metadata.

**Comment by cooperlees** [comment]
Sure. PR welcome. If Unit Tests and CI passes I will be more than happy to merge.

**Comment by cooperlees** [comment]
Do you have any aspirations or have started working on this?

**Comment by lepaperwan** [comment]
I don't know PyOxidizer so don't know the exact requirements it has but supporting the __main__ interface seems as simple as adding a __main__.py to the module with:
```python
from . import main

exit(main.main())
```

This effectively allows bandersnatch to be invoked with `python -m bandersnatch mirror` or whatever bandersnatch command needs to be run. The only minor issue is that ArgumentParser derives `prog` from `sys.argv[0]` so `python -m bandersnatch --help` outputs `usage: __main__.py [-h] ...`.

**Comment by rkm** [comment]
I tested this out and it seems to work. The ArgumentParser help name can be overridden with the `prog` argument:

```diff
diff --git a/src/bandersnatch/__main__.py b/src/bandersnatch/__main__.py
new file mode 100644
index 0000000..8587444
--- /dev/null
+++ b/src/bandersnatch/__main__.py
@@ -0,0 +1,2 @@
+from . import main
+exit(main.main())
diff --git a/src/bandersnatch/main.py b/src/bandersnatch/main.py
index b6829e6..669adde 100644
--- a/src/bandersnatch/main.py
+++ b/src/bandersnatch/main.py
@@ -143,7 +143,7 @@ async def async_main(args: argparse.Namespace, config: ConfigParser) -> int:


 def main(loop: Optional[asyncio.AbstractEventLoop] = None) -> int:
-    parser = argparse.ArgumentParser(description="PyPI PEP 381 mirroring client.")
+    parser = argparse.ArgumentParser(description="PyPI PEP 381 mirroring client.", prog="bandersnatch")
     parser.add_argument(
         "--version", action="version", version=f"%(prog)s {bandersnatch.__version__}"
     )
```

I can create a PR if this would work for you?

**Comment by cooperlees** [comment]
I don't know if that will help this oxidized environment, but if it breaks no CI then I would accept.
