### ISSUE TITLE
Problems with 'runner.py'

### ISSUE THREAD

**Issue by GreatBahram** [pypa/bandersnatch#393]
Hello there,

I noticed these problems in the `runner.py` while I was using the docker image:

https://github.com/pypa/bandersnatch/blob/1b573a141fd6ee4b171c612b1422089b119e544f/src/runner.py#L27

* Firstly, args doesn't have a `conf` attribute, it has been defined as `config`.
* Secondly, I think, It's not a good idea to hardcode the `bandersnatch` path. Because even in the Docker image you'll find the `bandersnatch` inside `/usr/local/bin/`

* Thirdly, the `interval` type should be `int` not `str`:
https://github.com/pypa/bandersnatch/blob/1b573a141fd6ee4b171c612b1422089b119e544f/src/runner.py#L21

* Because, this line will show an error if you execute it:
https://github.com/pypa/bandersnatch/blob/1b573a141fd6ee4b171c612b1422089b119e544f/src/runner.py#L28

Even when I solved the above problems in my container, I got another error. My question is, why don't you guys utilize the default configuration when the configuration hasn't been given?
```bash
2020-01-04 16:00:45,222 WARNING: Config file '/conf/bandersnatch.conf' missing, creating default config.
2020-01-04 16:00:45,222 WARNING: Please review the config file, then run 'bandersnatch' again.
2020-01-04 16:00:45,222 ERROR: Could not create config file: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/bandersnatch/default.conf'
Sleeping for 3599.6514344215393s

```

**Comment by cooperlees** [comment]
Hi! Thanks for reporting. I’ll eventually get to fixing this, but a PR is welcome anytime. Some clowny mistakes there.

P.s. I did docker to learn it - being at Facebook I hardly get to use docker.

**Comment by GreatBahram** [comment]
Hi there, 

I tried to solve them, but I reckon we could achieve the configuration problem by adding some changes to Dockefile.

Let me know if there is any problem with the pull request.

**Comment by cooperlees** [comment]
Suggest away to make the Docker file better :D You're the first verbose user so happy to solve your needs :)

**Comment by cooperlees** [comment]
Pushed https://github.com/pypa/bandersnatch/commit/2ba069d5e7f57ce47b011d7fcbef5e68be160e09 to do everything but the described configuration problem.

I'd still prefer people bind mount in their config file to the Docker container.

**Comment by GreatBahram** [comment]
Thanks, I pulled the new image, but I got below error message:
```
Config file '/conf/bandersnatch.conf' missing, creating default config.
Please review the config file, then run 'bandersnatch' again.
Could not create config file: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/bandersnatch/default.conf'
Running bandersnatch every 3600s
```
I checked the `setup.cfg` and it contains the `include_package_data = True` option, but it seems it hasn't been copied the `default.conf` file into the container, as I checked and the result was this:
```bash
root@dc6188d1df3d:/usr/local/lib/python3.8/site-packages/bandersnatch# ls 
__init__.py  configuration.py  filter.py  main.py    mirror.py   utils.py
__pycache__  delete.py         log.py     master.py  package.py  verify.py
```
Do you have any idea on this?

**Comment by cooperlees** [comment]
- `default.conf` is definitely in the sdist (just tested)
- `default.conf` is in the container when I build it locally on my Mac laptop

To check I ran:
- docker build .
- docker run -d d102a7232046 sleep 3600
- docker exec -it 443a66e7c0f363034fdbb2e0c7bc464c3f0cef5a85ee5341ed7e4c6588d79d3e bash
- 

```
root@443a66e7c0f3:/# ls -lh /usr/local/lib/python3.8/site-packages/bandersnatch/default.conf
-rw-r--r-- 1 root root 3.3K Sep 14 14:49 /usr/local/lib/python3.8/site-packages/bandersnatch/default.conf
```

I still feel before you `docker run` you should create your own `bandersnatch.conf` on the host machine and bind mount that into `/conf` or somewhere else and specify that rather than using the default CMD.

Where are you storing the packages / web tree? Surely in a volume or bind mount? Maybe put the config in there too?

I've put up a PR to create an empty /conf, as maybe the log message was misleading and since /conf does not exist could not copy it there (I was lazy and didn't check the code).
https://github.com/pypa/bandersnatch/pull/400

**Comment by GreatBahram** [comment]
Very sorry for the delayed response, Here's the result of mine.
* First of all, earlier I didn't build the image locally, I pulled it from the docker hub.
* But now I cloned the project, and ran your instructions on my computer:

```shell
# After building the image from Dockerfile, I got this Image ID '02bc24a11856', then:
➜  bandersnatch git:(master) docker run -it 02bc24a11856 /bin/bash 
root@1ace34cb6716:/# python3 --version
Python 3.8.1
root@1ace34cb6716:/# ls /usr/local/lib/python3.8/site-packages/bandersnatch
__init__.py  __pycache__  configuration.py  delete.py  filter.py  log.py  main.py  master.py  mirror.py  package.py  utils.py  verify.py
```
* However, my operating system is Ubuntu (19.10), I'm not sure if it has some side-effects on the result or not.
* Then I ran `python3 setup.py sdist` to check it manually, and everything was fine! I really don't understand why this file (`default.conf`) does not exist in the image.
```shell
➜  bandersnatch git:(master) tar tf dist/bandersnatch-3.6.0.tar.gz | grep default.conf
bandersnatch-3.6.0/src/bandersnatch/default.conf
```
* By the way, I checked your PR and everything was fine, thanks for that.

**Comment by cooperlees** [comment]
So, are you able to use the Docker Image yet? If not I might have to dig into what commands the GitHub actions uses to publish and see if I can workout why the default.conf is not being included. I find it hard to understand how that's possible.

If you're all good please close this issue.

**Comment by GreatBahram** [comment]
Today, again, I pulled the latest bandersnatch image from the docker hub:
```bash
➜  ~ docker pull pypa/bandersnatch
Digest: sha256:d6e6d46c54269881be4bb9a7b522e8148fff3d28a041214962166e91d1a88d69
Status: Downloaded newer image for pypa/bandersnatch:latest
docker.io/pypa/bandersnatch:latest

➜  ~ docker run -it pypa/bandersnatch 
Running bandersnatch every 3600s
Config file '/conf/bandersnatch.conf' missing, creating default config.
Please review the config file, then run 'bandersnatch' again.
Could not create config file: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/bandersnatch/default.conf'

➜  ~  # Then I examined the image manually, the result:

➜  ~ docker run -it pypa/bandersnatch /bin/bash
root@0bdc2ab9ed48:/# ls /usr/local/lib/python3.8/si
signal.py      site-packages/ site.py        
root@0bdc2ab9ed48:/# ls /usr/local/lib/python3.8/site-packages/bandersnatch
__init__.py  __pycache__  configuration.py  delete.py  filter.py  log.py  main.py  master.py  mirror.py  package.py  utils.py  verify.py
root@0bdc2ab9ed48:/# 
```

I don't know what the problem is, but I couldn't find the `default.conf` inside the bandersnatch module.

**Comment by SanketDG** [comment]
@cooperlees Maybe this is was the same issue that was fixed in https://github.com/pypa/bandersnatch/pull/519

**Comment by cooperlees** [comment]
Yeah looks it. Reopen if not the case.

**Comment by GreatBahram** [comment]
I checked it, it has been solved!

Thanks
