### ISSUE TITLE
Fix test_package_sync_does_not_touch_existing_local_file to occasionally failing

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#453]
This is randomly failing, need to workout why. Could be a race, could be a number of things.

stat should not differ but sometimes is. Lets see what part of stat differs - It's hard to repro locally.

Example Fail: https://github.com/pypa/bandersnatch/pull/451/checks?check_run_id=504352574

**Comment by cooperlees** [comment]
Another failure. Seems to always only be >= 3.8: https://github.com/pypa/bandersnatch/pull/460/checks?check_run_id=517003207

Will try get 3.8 on my Mac and try repro later today. All local dev I've been using 3.7

**Comment by cooperlees** [comment]
This is still occurring on CI - I'd love a second set of eye to take a look at this to try help find my bug!

**Comment by SanketDG** [comment]
Is there any consistent way of making this fail on CI?

Once it fails for a certain push, does it fail for a second push in a PR?

If that is the case, then we can use the [`stat`](https://docs.python.org/3/library/stat.html) module to inspect what exactly is different.

**Comment by SanketDG** [comment]
Opened https://github.com/pypa/bandersnatch/pull/487 for debugging this.

From https://travis-ci.org/github/pypa/bandersnatch/jobs/674697261:

```
OLD STAT: os.stat_result(st_mode=33204, st_ino=2562282, st_dev=2049, st_nlink=1, st_uid=2000, st_gid=2000, st_size=0, st_atime=1586837095, st_mtime=1586837095, st_ctime=1586837095)
NEW STAT:os.stat_result(st_mode=33204, st_ino=2562282, st_dev=2049, st_nlink=1, st_uid=2000, st_gid=2000, st_size=0, st_atime=1586837096, st_mtime=1586837095, st_ctime=1586837095)
```

Looks like the access time differs by a second, can we mock this?
