### ISSUE TITLE
Bandersnatch raises exception when syncing pypi package with mixed case

### ISSUE THREAD

**Issue by FaustinCarter** [pypa/bandersnatch#470]
When trying to sync a package that is listed on PyPI with a non-canonical name (i.e. mixed case), bandersnatch will error out with the following exception. Example, the `pyGTC` package:

```
2020-03-26 10:28:49,379 ERROR: Error syncing package: pygtc@3330176
Traceback (most recent call last):
  File "c:\users\fwcarter\desktop\code\bandersnatch\src\bandersnatch\package.py", line 173, in sync
    self.mirror.record_finished_package(self.name)
  File "c:\users\fwcarter\desktop\code\bandersnatch\src\bandersnatch\mirror.py", line 255, in record_finished_package
    del self.packages_to_sync[name]
KeyError: 'pygtc'
```

The problem can be solved by changing `self.name` to `self.raw_name` in the following line of code.

https://github.com/pypa/bandersnatch/blob/b3f6701bcfc2fec833e50404d86b0dc96e241646/src/bandersnatch/package.py#L170

However, a better approach might be to canonicalize the names that are used as dict keys before they get used as dict keys here:

https://github.com/pypa/bandersnatch/blob/b3f6701bcfc2fec833e50404d86b0dc96e241646/src/bandersnatch/mirror.py#L195-L196

A corollary to this bug is that if one tries to whitelist a package with the canoncialized name, rather than the raw name in PyPI, then bandersnatch will fail even to find the package on PyPI. I have not tracked this down yet, but it should be considered part of this issue.

**Comment by cooperlees** [comment]
Thanks for finding these bugs! I knew I'd miss something and the PR for this was just recently done by myself.

Simplicity says normalizing as early as possible (e.g. on external I/O) is the best thing to do. I will try and get a PR up to try doing this in the next few days. We will just have to live with the generated HTML having only the normalized name and forget about the raw_name concept.

For the plugin, we will just have to state we can only filter based via PEP normalized names.

Please correct anything if I am wrong.

**Comment by cooperlees** [comment]
Actually, for the plugin, we should just also normalize on initialization - Then humans can put in non normalized and they will still work.

**Comment by cooperlees** [comment]
Updated docs to show Case is important for filters for now. 4.1 might get the big refactor. Needed to get a release out as way to much has changed.

https://github.com/pypa/bandersnatch/pull/474
