### ISSUE TITLE
deleted packages on pypi cause sync failure

### ISSUE THREAD

**Issue by windtail** [pypa/bandersnatch#494]
This maybe a bug of aiohttp, but i am not familiar with aiohttp.

The following lines in `Master::get` function 

```python
        async with self.session.get(path, timeout=timeout, **kw) as r:
            got_serial = (
                int(r.headers[PYPI_SERIAL_HEADER])
                if PYPI_SERIAL_HEADER in r.headers
                else None
            )
            await self.check_for_stale_cache(path, required_serial, got_serial)
            yield r
```

if `r.status == 404`, `aiohttp.ClientResponseError` is **NOT** raised, instead `StalePage` is raised later, so the condition of deleted packages is not detected correctly

**Comment by windtail** [comment]
The following hack may fix this
```patch
Index: src/bandersnatch/master.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/bandersnatch/master.py	(revision 3fcdc9fd0722fd06bc0ecfdda3704371a57f5ae8)
+++ src/bandersnatch/master.py	(revision 7418eb2f05491e8d484291174d0f9c9e0065eb52)
@@ -104,6 +104,8 @@
             del kw["timeout"]
 
         async with self.session.get(path, timeout=timeout, **kw) as r:
+            if r.status != 200:
+                raise aiohttp.ClientResponseError(r.request_info, r.history, status=r.status)
             got_serial = (
                 int(r.headers[PYPI_SERIAL_HEADER])
                 if PYPI_SERIAL_HEADER in r.headers
```

**Comment by cooperlees** [comment]
Hi,
Thanks for the report. I wonder if `requests` code I replaced with `aiohttp` had `raise_for_status()` in use and I missed it. Will check.

I think we can also set `raise_for_status=True` on the session or the individual requests as per:
https://docs.aiohttp.org/en/stable/client_reference.html

I'll accept a PR. Lets try setting it to `True` on the aiohttp `session` we create here:
https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/master.py#L44
- Then get a unittest/integration test to cover this so we don't break it again.

If you don't have time to PR I'll try get to it this week.

**Comment by windtail** [comment]
As my previous hack, if `aiohttp.ClientResponseError`  raised, package will be deleted.

And I just confirmed that `aiohttp.ClientResponseError` was raised by following code

```python
@pytest.mark.asyncio
async def test_404(master):
    import aiohttp
    with pytest.raises(aiohttp.ClientResponseError):
        async with master:
            async with master.session.get("https://pypi.org/pypi/aaaaaaa/json") as r:
                pass
```

**Comment by cooperlees** [comment]
Will release this today. Thanks again!
