### ISSUE TITLE
[QUESTION] How large is a full pypi mirror?

### ISSUE THREAD

**Issue by wayneworkman** [pypa/bandersnatch#50]
Just wondering. I'm at nearly 600GB right now - wondering how far there is to go.
Please date your responses as people in the future may come here for answers.

**Comment by cooperlees** [comment]
https://p.datadoghq.com/sb/7dc8b3250-85dcf667bd - Shows we're currenty at 2.04TB. You've got a ways to go.

@dstufft has opened https://github.com/pypa/warehouse/issues/4288 to show who the top N users are space wise so we can formulate a good blacklist to space people tons of space.
