### ISSUE TITLE
Lots of timeout error with same configuration after upgrading from 3.6.0 to 4.0.3

### ISSUE THREAD

**Issue by zxkane** [pypa/bandersnatch#511]
After checking the log of bandersnatch, I see hundreds of timeout errors like below when downloading artifacts from pypi.org in last 6 hours.

```
2020-05-11 13:11:09,902 ERROR: Continuing to next file after error downloading: https://files.pythonhosted.org/packages/40/5b/4c9539b8c316552aef2c35b53a483c3ca4d6afc03732cba1d45a601fb98e/bcml-3.0.0b4.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 288, in sync_release_files
    release_file["url"], release_file["digests"]["sha256"]
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 449, in download_file
    chunk = await response.content.read(chunk_size)
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/streams.py", line 368, in read
    await self._wait('read')
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

I checked the similar timeout error with terms `socket.timeout: The read operation timed out` and `Continuing to next file after error downloading:` in period 05/05-05/07(complete three days) when using 3.6.0, I just found timeout occurrences less than one hundred.

Indeed the host running bandersnatch has slow download speed from `files.pythonhosted.org`, but I tried to download some artifacts(the size from 16MB to ~500MB) from pypi server via `wget`. The files always were downloaded successfully without any retry. See logs of some attempts below,
``` bash
wget https://files.pythonhosted.org/packages/fa/24/fa02a26cfd3fce40c0777d886a5b6fd079c9bbf0e504e64405399b34ce0e/dgl_cu101-0.5a200508-cp38-cp38-manylinux1_x86_64.whl
--2020-05-09 04:41:52--  https://files.pythonhosted.org/packages/fa/24/fa02a26cfd3fce40c0777d886a5b6fd079c9bbf0e504e64405399b34ce0e/dgl_cu101-0.5a200508-cp38-cp38-manylinux1_x86_64.whl
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.109.63, 2a04:4e42:1a::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.109.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16960670 (16M) [application/octet-stream]
Saving to: ‘dgl_cu101-0.5a200508-cp38-cp38-manylinux1_x86_64.whl’

100%[====================================================================================================================>] 16,960,670  37.7KB/s   in 8m 49s

2020-05-09 04:50:42 (31.3 KB/s) - ‘dgl_cu101-0.5a200508-cp38-cp38-manylinux1_x86_64.whl’ saved [16960670/16960670]

wget https://files.pythonhosted.org/packages/1b/14/cf8859bcf64790861ef22155dc28db9e965b989325e9b99908934031a83b/tf_nightly_gpu-2.2.0.dev20200508-cp38-cp38-manylinux2010_x86_64.whl
--2020-05-09 03:44:01--  https://files.pythonhosted.org/packages/1b/14/cf8859bcf64790861ef22155dc28db9e965b989325e9b99908934031a83b/tf_nightly_gpu-2.2.0.dev20200508-cp38-cp38-manylinux2010_x86_64.whl
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.109.63, 2a04:4e42:36::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.109.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 521957498 (498M) [application/octet-stream]
Saving to: ‘tf_nightly_gpu-2.2.0.dev20200508-cp38-cp38-manylinux2010_x86_64.whl’

100%[====================================================================================================================>] 521,957,498 44.7KB/s   in 2h 36m d

2020-05-09 06:20:25 (54.3 KB/s) - ‘tf_nightly_gpu-2.2.0.dev20200508-cp38-cp38-manylinux2010_x86_64.whl’ saved [521957498/521957498]

wget https://files.pythonhosted.org/packages/40/5b/4c9539b8c316552aef2c35b53a483c3ca4d6afc03732cba1d45a601fb98e/bcml-3.0.0b4.tar.gz
--2020-05-11 13:40:40--  https://files.pythonhosted.org/packages/40/5b/4c9539b8c316552aef2c35b53a483c3ca4d6afc03732cba1d45a601fb98e/bcml-3.0.0b4.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.109.63, 2a04:4e42:1a::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.109.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24551783 (23M) [application/x-tar]
Saving to: ‘bcml-3.0.0b4.tar.gz’

100%[====================================================================================================================>] 24,551,783  26.1KB/s   in 25m 48s

2020-05-11 14:06:30 (15.5 KB/s) - ‘bcml-3.0.0b4.tar.gz’ saved [24551783/24551783]
```

The configuration for 3.6.0 is 10 workers with 15 seconds timeout. After upgrading to 4.0.3, I already tune the timeout much longer(120 seconds currently). The large amount of timeout significantly impacts the mirroring progress from upstream. 

Is there any suggestion to improve it?

**Comment by cooperlees** [comment]
With the speeds you’re getting (seen via wget) I’d suggest stay with the 15 second timeout and less workers. I suggested this on another issue.

Have you tried with just 2 workers? With wget you only have 1 download going at a time ...

The other things we could try are:
- changing the chunk size aiohttp is using here:
https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/package.py#L414
  - for your connection maybe 64kb is to large

- use more timeout options aiohttp offers to suit your connection:

https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts

https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/master.py#L38

I can not replicate this issue easily as I have fast connections. I’m going to need your help to fine a more reliable setting for you and then we can make it configurable.

**Comment by zxkane** [comment]
Cooper, thanks for your prompt response. I'll follow your suggestion to tune it more.

If you would like to play with it more, you can share me a ssh public key via mailto:me@kane.mx. I can set up a clean env for you with similar network environment.

**Comment by MikeHofmann** [comment]
I think the root cause is because of: https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/master.py#L38 setting the **total** timeout to whatever value is in `bandersnatch.conf`. While a low value like 10s might be enough for small packages on a fast connection, it might be not enough for big packages and a lot of workers.

From from linked documentation of the `aiohttp`-library, i personally think it might be better to do a

```python
aiohttp_timeout = aiohttp.ClientTimeout(sock_connect=self.timeout, sock_read=self.timeout)
```

This would preserve the nature of bandersnatch's timeout value not blocking on stale connections, but hopefully give large packages enough time to download.

**Comment by zxkane** [comment]
I agree with Mike's suggestion. The number of workers and the size of download chuck are not root caused of timeout error.

I made [a rough fix](#514) to change the `total` timeout larger for allowing downloading artifacts in my network environment. After running bandersnatch with it for hours, looks like it works as expected.

I still see few timeout errors like below probably caused by current timeout setting(15 seconds),
```
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://pypi.python.org//pypi/torchdata-nightly/json

aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://files.pythonhosted.org/packages/96/2d/45f499330edbacbf2ebe293436bcc5c6a004fc0175f848948f6b87ef2171/tff_nightly-0.0.1.dev20200512-py2.py3-none-any.whl

2020-05-12 12:07:12,089 ERROR: Continuing to next file after error downloading: https://files.pythonhosted.org/packages/8b/84/ec341a3ff601b9abe2ff6d01a3f15e08da272ecaf6804fef9232f9c8efa5/esig-0.7.1-cp38-cp38-manylinux1_i686.whl
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 288, in sync_release_files
    release_file["url"], release_file["digests"]["sha256"]
  File "/usr/local/lib/python3.7/site-packages/bandersnatch/package.py", line 449, in download_file
    chunk = await response.content.read(chunk_size)
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/streams.py", line 368, in read
    await self._wait('read')
  File "/usr/local/lib64/python3.7/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket
```

**Comment by cooperlees** [comment]
Cool. So that last timeout actually looks like that socket legitimately was unable to pull any data for the timeout seconds. Then this should hopefully succeed on the next run.

I believe number of workers still helping cause you to get some timeouts on your limited connection. If your connection can only do 50kbps and you have 10 workers getting 5kbps each, there is way more chance for a package or two to get starved.

**Comment by cooperlees** [comment]
^^ Will accept an optional total multiplier or a dedicated total_timeout param added to configuration file if people feel there are useful use cases.
