### ISSUE TITLE
Documetation: Add section about 4.1's storage abstraction and new support

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#552]
We now have a new storage abstraction. We need to document that and:
- Tradition Filesystem support
- Swift support
- S3 Support

Topics could include and are not limited to:
- Config 
- Flow
- Known limitations etc.

**Comment by LeoQuote** [comment]
Hi, do we have documents for storage abstraction ? I'm really looking foward to the s3 support

**Comment by cooperlees** [comment]
The PRs would have been linked here if they ever came for the documentation.

Unfortunately S3 support was never contributed. PRs welcome, the abstraction layer is all there for easy adoption of the S3 API.

**Comment by cooperlees** [comment]
#1006 adds very basic (far from complete) documentation.

**Comment by cooperlees** [comment]
We have most of this. Will take enhancements of always.
https://bandersnatch.readthedocs.io/en/latest/storage_options.html
