### ISSUE TITLE
Add ‘sync’ sub command to bandersnatch

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#560]
I saw someone made a hack to bandersnatch to be able to ask it to sync a certain package echo’s into a file.

I feel we could go one step further and make:
- ‘bandersnatch sync pkg1 pkg2 ...’
Or
- ‘bandersnatch sync /path/to/file’
  - file could be a list of white space package names OR maybe even a requirements file

**Comment by dralley** [comment]
How would this be different from the functionality ```pip download pkg1 pkg2``` or ```pip download -r requirements.txt``` provides?

**Comment by cooperlees** [comment]
This downloads ALL a packages releases for the mirror, not for the user. This allows someone to force a repair or use the CLI to give a list of projects they want to sync.

People can do their own filtering and not use bandersnatch plugins too.

**Comment by dralley** [comment]
Ah, makes sense.

**Comment by cooperlees** [comment]
#572 does this!
