### ISSUE TITLE
Bandersnatch not able to pull tensorflow binary

### ISSUE THREAD

**Issue by goal86sg** [pypa/bandersnatch#567]
Referring to my attached bandersnatch.conf i am not able to pull down tensorflow and tensorflow-gpu binaries in the simple/ folder why is this so? In addition upon a successful pull of the python binaries, the mirror exit gracefully with a code 0.. Upon the next time i run a bandersnatch mirror --force-check again with the contents as per the last run, I get an exit code 1 with TypeError: must be a str or None not int why is this so?
[pp-pypi-mirror_config_bandersnatch.txt](https://github.com/pypa/bandersnatch/files/4749949/pp-pypi-mirror_config_bandersnatch.txt)

**Comment by goal86sg** [comment]
I solved this portion
"
In addition upon a successful pull of the python binaries, the mirror exit gracefully with a code 0.. Upon the next time i run a bandersnatch mirror --force-check again with the contents as per the last run, I get an exit code 1 with TypeError: must be a str or None"

by re-pulling the latest container image.

**Comment by cooperlees** [comment]
You don't need a blacklist if you have a whitelist. Please try removing affine from blacklist packages.

Only other thing I could imagine is the case sensitive nature maybe of the whitelist.

Can I see the full stack-trace you get when you run with `--force-check`. That should help finding that cli bug.

**Comment by goal86sg** [comment]
Hello,

thanks for reaching out! Yes exactly tensorflow are all in smallcases.I did a "locate -i tensorflow" in the binary folder which i pulled and managed to see the tensorflow binaries residing in the packages folder. I tried isolating by rewriting my bandersnatch.conf to whitelist tensorflow, tensorflow-gpu only and it is kind of the similar behaviour where it doesnt appear in the simple folder as a accessible link. Attaching the outputs of running --force-check many thanks!!!!
[output.txt](https://github.com/pypa/bandersnatch/files/4755609/output.txt)
[indexhtml.txt](https://github.com/pypa/bandersnatch/files/4755611/indexhtml.txt)

**Comment by cooperlees** [comment]
I’m sorry, but I don’t see a stack trace about the TypeError you speak of?

I’ll try when I next get time making a whitelist with the default configuration for tensorflow only and see if I can reproduce what you say. With a retro or a stack trace I don’t know how to fix this sorry.

**Comment by goal86sg** [comment]
Hello Cooper,

How do I get the stack trace out? Where does it reside?

Regards
Desmond

**Comment by cooperlees** [comment]
#571 might help you since you seem to say the same error ...

**Comment by goal86sg** [comment]
Hello Cooper,

only problem i have now is the whitelist of tensorflow or tensorflow-gpu
package that does not appear in the simple folder when it is downloaded.

Regards
Desmond

**Comment by cooperlees** [comment]
So I tried to repro, and here are all my steps. I was able to get all the tensorflow and tensorflow-gpu. All ~200gb of them. I only used the whitelist plugin and if it succeeds (spoiler it does - but after a few syncs) it can only leave the other plugins at fault and I'll need your help to debug what's going on there cause I can't possibly maintain all the plugins myself in my spare time.

## Steps taken

`mkdir /Volumes/c00pUp/pypi`

`vim src/bandersnatch/tests/ci.conf`

```diff
diff --git a/src/bandersnatch/tests/ci.conf b/src/bandersnatch/tests/ci.conf
index bae7821..b3f90fc 100644
--- a/src/bandersnatch/tests/ci.conf
+++ b/src/bandersnatch/tests/ci.conf
@@ -1,7 +1,7 @@
 ; Config for the Travis CI Integration Test that hits PyPI

 [mirror]
-directory = /tmp/pypi
+directory = /Volumes/c00pUp/pypi
 json = true
 cleanup = true
 master = https://pypi.org
@@ -20,9 +20,7 @@ enabled =

 [whitelist]
 packages =
-    ACMPlus
-    black
-    peerme
-    pyaib
+    tensorflow
+    tensorflow-gpu

 ; vim: set ft=cfg:
```

```
/tmp/test_bs_567/bin/pip install -r requirements.txt -r requirements_swift.txt -e .
/tmp/test_bs_567/bin/bandersnatch --config src/bandersnatch/tests/ci.conf --debug mirror

2020-06-17 15:46:07,210 INFO: Storing index page: tensorflow-gpu - in /Volumes/c00pUp/pypi/web/simple/t/tensorflow-gpu
2020-06-17 15:46:07,210 DEBUG: There are 54 releases for tensorflow-gpu

```

- Big download - thus the use of an external disk
```
203G	/Volumes/c00pUp/pypi
```

`find /Volumes/c00pUp/pypi/web/simple` output: https://pastebin.com/gjqGNHN9
`find /Volumes/c00pUp/pypi/` output: https://pastebin.com/617281eF


So, it did take a few syncs. But it all worked. So this shows it must be a bug in one of the other plugins you're using.

**Comment by goal86sg** [comment]
can you share with me your bandersnatch.conf file? that will be grateful thanks!

**Comment by goal86sg** [comment]
dont mind attaching here ur entire ci.conf file here for reference thanks!

**Comment by cooperlees** [comment]
@goal86sg - It's in the repo: https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/tests/ci.conf

This is why I pasted the Unix `diff` output to show the small changes I did.

**Comment by goal86sg** [comment]
i did a few round of test with and without the blacklist plugins but still ran to issues. I still dont see tensorflow appearing in the web/simple folder
[bandersnatch.txt](https://github.com/pypa/bandersnatch/files/4829049/bandersnatch.txt)
[withblacklist.txt](https://github.com/pypa/bandersnatch/files/4829044/withblacklist.txt)
[withoutblacklist.txt](https://github.com/pypa/bandersnatch/files/4829045/withoutblacklist.txt)

**Comment by goal86sg** [comment]
I tried a resync again is working as shown your result you provided earlier.. i suspect the blacklist plugins for the platforms could be the cause

**Comment by cooperlees** [comment]
If you ever find the actual cause please feel free to re-open.
