### ISSUE TITLE
More inclusive naming for whitelist and blacklist plugins

### ISSUE THREAD

**Issue by martintoreilly** [pypa/bandersnatch#569]
Can we use other terms than `whitelist` and `blacklist` to represent the list of packages we are allowing and blocking? I know these are only names and that these terms have established meanings within tech, but I feel that the association of good with white and bad with black has racist connotations and that we could use equally informative alternatives - e.g. `allow` and `deny` (following the convention with firewall rules) or `approved` and `forbidden`.

We're looking to make this change for all our internal references to whitelists and blacklists in one of our projects that uses bandersnatch to enforce these for Python packages, and we are happy to do the work to make equivalent changes to bandersnatch if they are agreed by the community. We recognise that we are new to the bandersnatch community and are looking to start a conversation on this and achieve a community consensus.

I recognise that we'll need to manage the introduction of any agreed change in terminology carefully to not break people's existing installations and will of course follow the standard bandersnatch practices for this.

**Comment by cooperlees** [comment]
Totally for this. I just ask that we support the current names and use some form of deprecation notice like I did for other configuration changes between 3.x and 4.x. Then for 5.0 we can remove. I’m not a fan of just breaking people with no warning for people who check for deprecation warnings.

Here is an example PR where I did this:
- https://github.com/pypa/bandersnatch/pull/225/files
- Here is removing it: https://github.com/pypa/bandersnatch/pull/446/files

I not to worried about the new names, but like allowlist and denylist. Simple and straight to the point I feel.

Thanks!

**Comment by dralley** [comment]
I'm slightly partial towards ```blocklist``` over ```denylist```, but either sounds fine to me.

```include_packages``` / ```exclude_packages``` also makes sense

**Comment by dralley** [comment]
Go (language) decided to use ```allowlist``` and ```blocklist``` https://go-review.googlesource.com/c/go/+/236857/

**Comment by martintoreilly** [comment]
> Go (language) decided to use `allowlist` and `blocklist` https://go-review.googlesource.com/c/go/+/236857/

I'm happy with `allowlist` and `blocklist`. 

[GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/7554) went with `allowlist` and `denylist`, but it looks like `allowlist` and `blocklist` is gaining ground as a consensus - it looks like its also the preferred option for [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1571734), [Chrome and Android](https://9to5google.com/2020/06/12/google-android-chrome-blacklist-blocklist-more-inclusive/), [nodejs](https://github.com/nodejs/node/pull/33813).

This [draft RFC](https://tools.ietf.org/id/draft-knodel-terminology-00.html#suggested-alternatives-1) also suggests these terms.

What's the process for community consensus / approval here? Happy if it's your call - just want to fit into the community practices.

**Comment by cooperlees** [comment]
I'll take any alternative. I don't see any PyPI standard so what whoever does the first working PR that handles the deprecation notice + reassignment will win :D
