### ISSUE TITLE
"todo" file is always removed

### ISSUE THREAD

**Issue by z4yx** [pypa/bandersnatch#570]
On current master branch, the following line

https://github.com/pypa/bandersnatch/blob/b3f0d742cfe6f82479e0d1f2c4e4aa0e9a6e0440/src/bandersnatch/mirror.py#L138

causes `TypeError: must be str or None, not int`, resulting in todo list being removed.

I found this line was introduced in commit 6aeec65971. Maybe the author wanted to write `.split(maxsplit=1)`, but omitted the argument mistakenly.

**Comment by techalchemy** [comment]
Thanks for giving me the benefit of the doubt ;) that is definitely what I intended
