### ISSUE TITLE
Make filesystem storage plugin more asyncio friendly

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#584]
Debugging a bug, I found that filesystem i/o is all serial and each function is synchronus and blocking on i/o.

Lets introduce a process / threadpool for asyncio to use to try up the i/o usage + eat more cpu.

Easy repro:
- Use whitelist to only download tensorflow (nice large wheels)
- Download 1/2 of tensorflow and cancel
- Restart, watch slow checksumming

I'm even using a slow USB hard disk on purpose too.

**Comment by lepaperwan** [comment]
I'm actually about to start working on this when I get some free time, how asyncio friendly do you actually see this?

`read`/`write` I/O should move to the executor for sure, but how about `unlink`/`rmdir`/`mkdir`/`stat`/`open`/`close`?

Timing 1000000 `open`/`close` cycles:

- tmpfs:
  - synchronous: 6.93761277 s
  - asynchronous: 17.00659905 s
- NFS:
  - synchronous: 17.39140390 s
  - asynchronous: 20.19312867 s

However making all calls `asyncio` friendly would allow for easier integration of remote storage backends like S3 or something else which would require performing API calls on most of them.

**Comment by cooperlees** [comment]
Happy to have them all wrapped in asyncio executors for filesystem and native async API calls for non POSIX/Windows filesystems.

I'd also planned to also introduce and extras install of [uvloop](https://pypi.org/project/uvloop/) as well to get some latency and speed wins.
