### ISSUE TITLE
verify's JSON updates keeps failures as valid JSON and never deletes packages

### ISSUE THREAD

**Issue by electricworry** [pypa/bandersnatch#62]
The --json-update parameter suffers from a couple of issues.

- If a package has been deleted, the response from pypi.org will be a 404 error page. This is saved to the JSON directory as if it is a success. Status should be checked to only save 200 responses.
- Furthermore, if a non-200 response is returned, if the --delete parameter is also set, then the original JSON file should be deleted so that it's files are recognised as orphans that need to be deleted.

**Comment by cooperlees** [comment]
#72 now addresses this - Thanks for raising and doing the PR.

**Comment by cooperlees** [comment]
Landed PR - Please open if issues persists.
