### ISSUE TITLE
Fix Docker release version tagging

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#672]
We don't seem to get version release tags still on the docker hub - https://hub.docker.com/r/pypa/bandersnatch/tags

I feel to achieve this we need to add on release upload like PyPI upload:
https://github.com/pypa/bandersnatch/blob/master/.github/workflows/pypi_upload.yml#L5
add here:
https://github.com/pypa/bandersnatch/blob/master/.github/workflows/docker_upload.yml#L3

**Comment by ichard26** [comment]
@cooperlees this seems to be fixed by 280e8dca3f8386b673ad20b0a84db5d2bfeaa4ed. Can we close this?

**Comment by cooperlees** [comment]
Yeah, I did fix this when moving bandersnatch to the same Docker upload as black. Thanks for the nudge.
