### ISSUE TITLE
Add support for `data-requires-python` attribute

### ISSUE THREAD

**Issue by zzh1996** [pypa/bandersnatch#68]
According to [PEP 503](https://www.python.org/dev/peps/pep-0503/)

> A repository MAY include a `data-requires-python` attribute on a file link. This exposes the `Requires-Python` metadata field, specified in PEP 345, for the corresponding release. Where this is present, installer tools SHOULD ignore the download when installing to a Python version that doesn't satisfy the requirement. For example:
> 
> `<a href="..." data-requires-python="&gt;=3">...</a>`
> In the attribute value, `<` and `>` have to be HTML encoded as `&lt;` and `&gt;`, respectively.

Without this feature, users will encounter errors because the latest version of a package may conflict with the running Python version.

e.g. using a mirror synced by bandersnatch
```
# python2 -m pip install ipython -U
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Collecting ipython
  Downloading https://mirrors.ustc.edu.cn/pypi/web/packages/5b/e3/4b3082bd7f6908af828561b0129b5064bff4a13e6acadb321fc2d939a605/ipython-7.0.1.tar.gz (5.1MB)
    100% |################################| 5.1MB 7.7MB/s 
    Complete output from command python setup.py egg_info:
    
    IPython 7.0+ supports Python 3.5 and above.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Python 3.3 and 3.4 were supported up to IPython 6.x.
    
    See IPython `README.rst` file for more information:
    
        https://github.com/ipython/ipython/blob/master/README.rst
    
    Python sys.version_info(major=2, minor=7, micro=15, releaselevel='candidate', serial=1) detected.
    
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Tm_NkK/ipython/
```

There will be no error if you switch to the official PyPI repository since `data-requires-python` attribute is provided.

**Comment by konetzed** [comment]
Any progress on this?

**Comment by cooperlees** [comment]
No. It's not been a priority of mine. It seems this also requires the maintainer to actually fill in the "requires-python" `setup.py/cfg` field. E.g. https://pypi.org/pypi/peerme/json is Python 3 only in the classifiers but I (as it's my package) didn't put in requires-python cause I didn't even know about it when I made this package years ago. So I don't feel it's going to be super high signal.

PR is welcome tho. You would basically:
- Check if json_api["info"]["requires_python"] is set
- If so, convert the versioning specifier to the HTML equivalent (Is there a library for this?)
- Add it into the metadata of the HTML generation

**Comment by konetzed** [comment]
Thank you for the code to fix this it is very much appreciated!  Is there a time frame for the next release date that will include these patches?

**Comment by cooperlees** [comment]
This will go out today in 3.3.0

**Comment by LeoQuote** [comment]
Hi, we recently upgraded bandersnatch from 1.6 to 3.6 , but there're tons of old index pages , how can I tell bandersnatch to update them all?

**Comment by cooperlees** [comment]
`bandersnatch mirror --force-check` should do the trick. Expect this to take some time.
