### ISSUE TITLE
Revert multidict to 4.7.6

### ISSUE THREAD

**Issue by lepaperwan** [pypa/bandersnatch#715]
Commit 3a81bd28cb51d74f42a5a9ac20f106a623a6bd9d bumped _multidict_ to 5.0.0 despite being incompatible with the pinned version of _aiohttp_ (3.6.2, at this time but it is also incompatible with 3.6.3) which requires ``multidict>=4.5,<5.0``.

I'm happy to submit a PR for it if required but given it's a simple revert I'm not sure it's necessary.

**Comment by cooperlees** [comment]
I will eventually get to this, but just haven't yet.

Reason I merged is my CI passed with the "buggy" Yarl. So I'm guessing bandersnatch does not hit the bugs with our simple aiohttp usage ...
