### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by kenneth-ux** [pypa/bandersnatch#743]
The library for blender is available on pydroid 3.
 I might be missing how to integrate since, I, freely am new at this.
 Python being free and blender being free; I would like to know how, if possible for a blender IDE environment to work on pydroid 3 IDE environment.
THANK YOU
kennethjamessenzekjr@gmail.com

**Comment by cooperlees** [comment]
Hi,
I had to Google what blender is. Where does bandersnatch come in on this? Do you want to mirror Python packages or something for Blender? Can you please explain in more detail who/where you see bandersnatch being "integrated".

Thanks.

**Comment by cooperlees** [comment]
Please reopen if you care to share more.
