### ISSUE TITLE
Create bandersnatch Travis Integration Tests

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#78]
Lets either hit test PyPI or an even smaller aiohttp `PyPI` to do a full sync (`mirror`) and a `verify` over to test code diffs. This might catch some things that Unit Tests will not. For Example:
- Hitting test PyPI will allow API changes to be found, but take longer + resources
- Hitting our own small `PyPI` will be faster but the API will need to be kept up to date + create more work.

I'm leaning towards hitting test PyPI - Thoughts?

**Comment by yeraydiazdiaz** [comment]
I also think using Test PyPI makes the most sense, unless the real PyPI includes some corner cases we'd like to cover.

Maybe we could use a specific integration test config with aggressive filtering for the sake of speed and disk usage. We could even have different builds and configs testing specific high level features.

**Comment by cooperlees** [comment]
Ok - we have an Integration test that should help pickup if a dependency module upgrade causes pain. This paves the way for #70
