### ISSUE TITLE
GitHub Actions Docker Upload is flaky

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#802]
Seems connection timeouts with pip from the few I've looked at. Would love some help if anyone has time to workout why the uploads are failing. Seems building the swift image in particular.

Example Fail: https://github.com/pypa/bandersnatch/runs/1697632568?check_suite_focus=true

**Comment by ichard26** [comment]
This is because of Pip's new dependency resolver that is a lot stricter when resolving dependencies. Unfortunately being strict means reading a bunch of metadata which is expensive since whole files have to be downloaded. Looks like we have a complex dependency tree situation on our hands...
