### ISSUE TITLE
Add CI to check for PR number entry in CHANGES

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#848]
Add CI to grep / re-search for the PR being mention in CHANGES.md

- Also update contributing documentation

**Comment by ichard26** [comment]
The main problem with this is that it's annoying to figure out what PR number your PR will be attached to unless you want to do at least two pushes.

**Comment by cooperlees** [comment]
We have this race today, it's just delayed and the poor maintainer pays. You either try guess the PR ID (which is doable unless the project is super busy) or just push 1 more commit when you see this fail.

I think the simplicity of this is a big winner. I think the pain of generally always having a failing CI to nudge the contributor to add the change log outweighs maintainer time to go back through and do it OR creating a much more complicated solution to check for the entry and possibly FILL IN the PR number. My main goal in CHANGES is to link back to PRs so people can see the code + discussion around it. I think this achieves this with minimal complexity.
