### ISSUE TITLE
Frequent timeout exceptions emitted from aiohttp

### ISSUE THREAD

**Issue by happyaron** [pypa/bandersnatch#864]
On our deployment we've observed frequent timeout exceptions emitted from aiohttp, with bandersnatch (4.4.0) + python (3.8.1):

In total 49 syncs:
1. `aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket` (49 times)
2. `aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host <url>` (20 times)
    (where <host> are urls to https://files.pythonhosted.org)
This might be related to https://github.com/aio-libs/aiohttp/issues/4549

Also there is another exception from aiohttp which does not show a direct indication to timeout:
1. `aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed` (25 times)
This might be related to https://github.com/aio-libs/aiohttp/issues/4581

Trying to use bandersnatch 3.6.0 (which uses asyncio w/ requests) + python (3.7.3), there's not any exceptions being raised.

Relevant parts of configuration look like this:
```
[mirrors]
json = true
timeout = 300
workers = 5
hash-index = false
stop-on-error = false
```

Our network has quite high latency than usual to reach to files.pythonhosted.org (~250ms rtt), while the latency is stable and packet loss is low). So we use a very long timeout setting in the configuration to make bandersnatch more patient to wait.

**Comment by cooperlees** [comment]
Hi,

Thanks for the report. This is always a hard thing to tune to be right for all so we're going to have to play with aiohttp here.

1)
Have you tried with less workers? Or do you need that to max out throughput due to the high latency?

2)
Are you able to try our docker image (thus move to Python 3.9) and see if that helps things with aiohttp on your connection?

Does bandersnatch eventually battle away and get all the packages, or does it never due to the many timeouts/exceptions?
- Please feel free to fork bandersnatch and try different aiohttp setting. Interested to see what else we can tune. I don't have a bad connection so I've never sat down to play with this.

Another hack I've done on bad connection in past lives:
- Get a close VPS that's on a good connect and put a Forward Proxy there like squid

**Comment by happyaron** [comment]
I tried the docker image with Python 3.9 with 20 syncs, the exceptions occur with similar rate, no real difference comparing to the Python 3.8 version.

bandersnatch could continue to download other packages because of the `stop-on-error = false` setting, but the package is not fully synchronized (the file with exception happening is not retried again), and subsequent syncs could not detect the problem. I guess this could be only fixed with a _verify_ run.

**Comment by cooperlees** [comment]
Ok, I feel that rules out the 3.8 specific aiohttp issues you linked then.

bandernsatch won't update it's TODO + Serial file until a successful run. So it should keep retrying all the packages that failed until successful. If not, we have a bug.

I feel here you'll need to play with each aiohttp timeout or packet capture to see where you're stalling and tune that timer. The exception should give some hint (you've supplied me with none so I can't help there). Every box I have access to have good connections all over the world and the PyPI CDN seems close, so hard for me to tune.

**Comment by happyaron** [comment]
Haven't yet been able to look into more log details, but the issues mentioned is not 3.8 specific, but first appearing since 3.8...

**Comment by happyaron** [comment]
Working with @shankerwangmiao, we captured the traffic between our instance of bandersnatch and pypi.org in the attached pcap file, and discovered this behavior:

1. bandernatch opens a keep-alive connection to the server and requested a URL (No. 225)
2. server responses, in the example a 301 Redirect (No. 229)
3. bandersnatch didn't response after 600 seconds, so the server issues a TLS Close Notify to close the connection (No. 231)
4. after another ~6300 seconds (total 6900 seconds), bandersnatch replied the server with TCP FINACK, however the server didn't response (No. 235-244)

Although in the 4th step the server should return RST at least, maybe the load balancer in front of pypi.org servers slightly breaks the stack, the above sequence suggests that bandersnatch didn't interact with the TCP connection in time. So we tried to see in the logs about what bandersnatch is doing:

1. At the same time packet No. 225 is sent, we have this log entry:

> 2021-04-02 21:01:45,191 INFO: Fetching metadata for package: chianwia1 (serial 9915466)

2. Going down a few more lines, we see a big lap happened in the log:

> 2021-04-02 21:01:45,483 INFO: Removing file: /data/mirrors/pypi/web/json/.catboost-dev.muldisqr
> 2021-04-02 22:56:52,115 INFO: Downloading: https://files.pythonhosted.org/packages/1f/53/5f03927fce8d36b5d4aede2e0f1c775b5d3f16af739f0a67483a2eabc20b/catboost_dev-0.20.1.8858-cp27-none-manylinux1_x86_64.whl

The time lap is about 6900 seconds. 

3. Soon we received the exception:

> 2021-04-02 22:56:52,123 ERROR: Error syncing package: chianwia1@9915466
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/bandersnatch/mirror.py", line 131, in package_syncer
>     await package.update_metadata(self.master, attempts=3)
>   File "/usr/local/lib/python3.9/site-packages/bandersnatch/package.py", line 60, in update_metadata
>     self._metadata = await master.get_package_metadata(
>   File "/usr/local/lib/python3.9/site-packages/bandersnatch/master.py", line 232, in get_package_metadata
>     metadata_response = await metadata_generator.asend(None)
>   File "/usr/local/lib/python3.9/site-packages/bandersnatch/master.py", line 144, in get
>     async with self.session.get(path, **kw) as r:
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
>     await resp.start(conn)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
>     message, payload = await self._protocol.read()  # type: ignore
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
>     await self._waiter
> aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

We suspect this is caused due to the thread event loop exists is occupied by other tasks for very long time so that aiohttp is not scheduled to run. So we tried to put `storage_backend.get_hash()` calls from `download_files()` into pool executor, to avoid the synchornize IO operations to occupie the event loop thread. After some time of testing the problem vanished.

[stream_326.pcapng.gz](https://github.com/pypa/bandersnatch/files/6309930/stream_326.pcapng.gz)
[pypi_2021-04-03_05_00.log.fail.gz](https://github.com/pypa/bandersnatch/files/6310055/pypi_2021-04-03_05_00.log.fail.gz)

**Comment by happyaron** [comment]
Reading through the issue list, this issue is actually the same thing in pypa/bandersnatch#584, while my PR resolves only the most potentially error-causing step (get_hash, which reads the whole file content and gets checksum).

I have thought about whether to wrap every storage backend operation into executor, but I'm tempered to prefer refactoring the backend code to be async friendly (like maybe using aiofiles for filesystem backend).

**Comment by cooperlees** [comment]
Very nice debugging and great aligning between a useful bandersnatch log + tcpdump. You never mentioned your I/O where you're storing the data or CPU to be very slow. Handy to remember in future people debugging similar behavior.

`aiofiles` I'm torn as it's another dependency, and all it really does is use executors too (with a few other fancy tricks to fake async + yield the event loop from time to time). I've always been a fan to just wrap all I/O in executors to keep dependency down, but yes we need to do this. Maybe I'll try hammer this out and get 5.0 out.
