### ISSUE TITLE
Automate Bandersnatch Docker Image Building

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#88]
Docker is the hotness. We should create a Docker image on the Docker Hub / Registry for all to use.

**Comment by cooperlees** [comment]
https://github.com/pypa/bandersnatch/pull/386 Has made this happen on master.

We should now make an action to tag releases on Docker Hub on GitHub release creation.

**Comment by SanketDG** [comment]
> We should now make an action to tag releases on Docker Hub on GitHub release creation.

Looks like this can be easily done with a easy combination of https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release and https://github.com/elgohr/Publish-Docker-Github-Action

Do you want me to go ahead and work on this?

**Comment by cooperlees** [comment]
Please! Awesome.
