### ISSUE TITLE
Look at keeping X old index.html files for package and main Simple API html

### ISSUE THREAD

**Issue by cooperlees** [pypa/bandersnatch#9]
We should add some protection from upstream changes causing blank index.html files to be generated. For example:

https://github.com/pypa/warehouse/issues/3551 (Although this particular scenario seems intentional).
Lets come up with an archiving system that keeps X (x == int set in config file) copies of index.html so we can compare changes over time and restore if needed locally.

0 == disabled feature.

**Comment by ewdurbin** [comment]
Options for naming the file:

* Integer: Similar to the way `logrotate` names files: `index.html`, `index.1.html`, `index.2.html`...
* Serial: Use the serial that generated the file: `index.html`, `index.4343751.html`, `index.434000.html`...
* Timestamp: Use the time the file was generated: `index.html`, `index.2018-10-28T15:42:56Z.html`...

Serial is probably the "right choice", but Timestamp has the advantage of being way more human friendly.

I'd also recommend considering generating the files and just symlinking `index.html` to the correct one. That might make things a bit simpler than swapping files?
