### ISSUE TITLE
bandersnatch_docker_upload should only run on PR or official repo

### ISSUE THREAD

**Issue by happyaron** [pypa/bandersnatch#934]
bandersnatch_docker_upload is now in the Actions list of forked repos, which I guess is not supposed to happen.

**Comment by cooperlees** [comment]
Is there a way to mark Actions to not go to forks? What are we supposed to do here?

I would imagine the docker upload runs, but fails due to no secret tho, right?

**Comment by ichard26** [comment]
This should be possible with a conditional but I don't think it will look very pretty haha. Personally I just manually disable any not useful for forks workflows from running on my fork. 

I'll look into this.
