### ISSUE TITLE
bandersnatch script crashes with remaining 32448 items  in TODO

### ISSUE THREAD

**Issue by ksanwar** [pypa/bandersnatch#958]
Hi,
I am trying to create an air gapped repo. I have downloaded about 7TB of packages but the script keeps failing with memory error.
Does bandersnatch maintain package dependencies? Do whatever packages I have downloaded so far have their dependencies downloaded as well? Trying to determine if my currently downloaded files are useable with all dependencies resolved.

thanks,
Kazi

**Comment by cooperlees** [comment]
Hi,

What's the error you're getting, your config and your platform (operating system)? How much memory is available to bandersnatch?

Unfortunately, bandersnatch is not dependency aware. I was hoping to one day make a plugin using the new [pip resolver](https://pip.pypa.io/en/latest/user_guide/#resolver-changes-2020) but it seems to not have a friendly public API for this use.

If are you able to profile the memory to see what's being used could also possibly help us see if we can tune what's stored in memory too.
- Maybe could use mprof? https://pypi.org/project/memory-profiler/

**Comment by cooperlees** [comment]
Please re-open if you ever want to give more info etc.
